<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sivonney Lillo Godoy">

<title>Desigualdad y Participación Política</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="desigualdad-pp2_files/libs/clipboard/clipboard.min.js"></script>
<script src="desigualdad-pp2_files/libs/quarto-html/quarto.js"></script>
<script src="desigualdad-pp2_files/libs/quarto-html/popper.min.js"></script>
<script src="desigualdad-pp2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="desigualdad-pp2_files/libs/quarto-html/anchor.min.js"></script>
<link href="desigualdad-pp2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="desigualdad-pp2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="desigualdad-pp2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="desigualdad-pp2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="desigualdad-pp2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Desigualdad y Participación Política</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sivonney Lillo Godoy </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="tendencias-de-desigualdad-y-participación-política-estudiantes-universitarios-en-chile" class="level1">
<h1>“Tendencias de Desigualdad y Participación Política: Estudiantes Universitarios en Chile”</h1>
<p>En el Chile actual, la desigualdad social y la estratificación económica han emergido como temas de alta relevancia sociológica, planteando desafíos significativos para la cohesión social y la justicia distributiva en las sociedades contemporáneas. La percepción de la desigualdad juega un papel crucial en la configuración de actitudes y comportamientos sociales y políticos de los individuos, y su impacto se refleja de manera notable en la participación política de la población.</p>
<p>La educación cívica y la política educativa se presentan como herramientas fundamentales para abordar esta problemática, ya que contribuyen a la formación de ciudadanos informados y comprometidos con el bienestar colectivo. En este contexto, comprender la relación entre la percepción de la desigualdad, la educación cívica y la participación política de estudiantes universitarios adquiere una relevancia particular, ya que estos jóvenes representan una parte importante de la población activa en la esfera política.</p>
<p>En este estudio, se propone analizar cómo la percepción de la desigualdad social influye en la participación política de los estudiantes universitarios en Chile. Diversas investigaciones indican que la participación política está estrechamente relacionada con el estatus socioeconómico, siendo aquellos con un nivel socioeconómico más alto más propensos a involucrarse en el sistema político.<span class="citation" data-cites="castilloSocialInequalityChanges2014">(<a href="#ref-castilloSocialInequalityChanges2014" role="doc-biblioref">Castillo et al. 2014</a>)</span> La desigualdad social en Chile ha sido un tema recurrente que ha generado tensiones y debates en la sociedad, contribuyendo a la fragmentación social y a la percepción de injusticia entre diferentes estratos de la población. Esta disparidad socioeconómica no solo ha impactado en la calidad de vida de los ciudadanos, sino también en su participación política y en la legitimidad de las instituciones democráticas.</p>
<p>Además, en la literatura existe una creciente preocupación por las menores tasas de participación electoral entre las cohortes de edad más joven. Por ejemplo, un estudio <span class="citation" data-cites="marchoogheVotersCandidatesFuture2013">(<a href="#ref-marchoogheVotersCandidatesFuture2013" role="doc-biblioref">Marc Hooghe et al. 2013</a>)</span> investigó la disposición a votar entre adolescentes de 14 años de 22 países europeos y encontró que, si bien la disposición a votar sigue siendo elevada en este grupo de edad, existe una clara división de género. Las niñas son más propensas a afirmar que votarán, mientras que los niños se ven más a sí mismos como futuros candidatos electorales. Un clima de aula abierta en la escuela contribuye a la voluntad de votar en futuras elecciones. Sin embargo, elementos que impactan en la participación de adultos no tienen un efecto significativo en la intención de votar entre adolescentes, lo que sugiere que la menor tasa de participación observada entre los más jóvenes no puede atribuirse simplemente a una falta de motivación política, sino que deben considerarse otros elementos para explicar esta tendencia a la baja.</p>
<p>“La evidencia empírica ha demostrado consistentemente que la participación política está relacionada positivamente con el entorno socioeconómico. Además, investigaciones recientes sugieren que los niños que provienen de familias de bajo estatus ya están menos dispuestos a involucrarse políticamente.” <span class="citation" data-cites="juancarloscastilloMitigatingPoliticalParticipation2015">(<a href="#ref-juancarloscastilloMitigatingPoliticalParticipation2015" role="doc-biblioref">Juan Carlos Castillo et al. 2015</a>)</span></p>
<p>Ligado a lo anterior, las influencias positivas de condiciones socioeconómicas más favorables representan un aumento del 36% en los puntajes de las pruebas escolares. Estos hallazgos sugieren que en el sistema educativo chileno, caracterizado por su segregación socioeconómica, estos efectos podrían contribuir a ampliar la brecha en el rendimiento académico en el ámbito de la educación cívica entre los estudiantes de escuelas con mayores recursos y aquellos con menos recursos. Además, este estudio revela que, en promedio, los estudiantes con un estatus socioeconómico más elevado son más susceptibles a estas influencias, y que los efectos de la composición socioeconómica son más pronunciados en el sector privado subvencionado que en el sector público. <span class="citation" data-cites="diegocolladoEffectsClassroomSocioeconomic2015">(<a href="#ref-diegocolladoEffectsClassroomSocioeconomic2015" role="doc-biblioref">Diego Collado et al. 2015</a>)</span></p>
<p>En ese sentido, la hipótesis central que orientará esta investigación es que a medida que aumenta el nivel de percepción de la desigualdad social entre los estudiantes universitarios, también aumenta su participación política. Se espera que la percepción de la desigualdad social actúe como un predictor principal de la participación política de estos jóvenes, motivándolos a comprometerse activamente en la esfera política para abogar por cambios sociales y económicos.</p>
<p>Para efectos de este trabajo, utilizaré datos obtenidos a través del Estudio Longuitudinal de Chile (ELSOC_ola2016), con el fin de observar como se comporta la participación política de los universitarios en Chile. Para ello, se considerarán aquellas personas que cursen una institución de educación superior, separandolos por Educación Técnica y Educación Universitaria.</p>
</section>
<section id="trabajo-en-r" class="level1">
<h1>Trabajo en R:</h1>
<section id="ajustes-iniciales" class="level2">
<h2 class="anchored" data-anchor-id="ajustes-iniciales">Ajustes Iniciales</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cargar-paquetes" class="level2">
<h2 class="anchored" data-anchor-id="cargar-paquetes">Cargar Paquetes</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sjlabelled,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>               dplyr, <span class="co">#Manipulacion de datos</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>               stargazer, <span class="co">#Tablas</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>               sjmisc, <span class="co"># Tablas</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>               summarytools, <span class="co"># Tablas</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>               kableExtra, <span class="co">#Tablas</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>               sjPlot, <span class="co">#Tablas y gráficos</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>               corrplot, <span class="co"># Correlaciones</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>               sessioninfo, <span class="co"># Información de la sesión de trabajo</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>               ggplot2)<span class="co"># Para la mayoría de los gráficos </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cargar-base" class="level2">
<h2 class="anchored" data-anchor-id="cargar-base">Cargar Base</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"Input/proc_data.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="eliminamos-casos-perdidos" class="level2">
<h2 class="anchored" data-anchor-id="eliminamos-casos-perdidos">Eliminamos casos perdidos</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">set_na</span>(., <span class="at">na =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">999</span>, <span class="sc">-</span><span class="dv">888</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(proc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="procesamiento-de-variables" class="level2">
<h2 class="anchored" data-anchor-id="procesamiento-de-variables">Procesamiento de Variables</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Procesamiento de Variables</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">set_na</span>(., <span class="at">na =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">999</span>, <span class="sc">-</span><span class="dv">888</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(proc_data)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(proc_data)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(proc_data, <span class="at">type=</span><span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=======================================
Statistic   N    Mean  St. Dev. Min Max
---------------------------------------
m0_sexo   1,805 1.603   0.489    1   2 
m0_edad   1,805 45.050  15.238  18  80 
m01       1,805 5.587   2.191    1  10 
c08_01    1,805 1.719   1.025    1   5 
c08_02    1,805 1.396   0.867    1   5 
c08_03    1,805 1.253   0.712    1   5 
c08_04    1,805 1.869   1.268    1   5 
c12_01    1,805 1.510   0.793    1   3 
c12_03    1,805 1.074   0.327    1   3 
c12_08    1,805 1.076   0.355    1   3 
c13       1,805 1.837   1.143    1   5 
c15       1,805 7.367   3.960    0  12 
c22       1,805 1.598   1.022    1   5 
c33       1,805 2.345   0.815    1   5 
---------------------------------------</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(proc_data,<span class="at">file =</span> <span class="st">"Input/proc_data.RData"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="do">##Nivel educacional</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>m01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=1805 valid N=1805 mean=5.59 sd=2.19

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 |  13 |  0.72 |    0.72 |   0.72
    2 | 143 |  7.92 |    7.92 |   8.64
    3 | 168 |  9.31 |    9.31 |  17.95
    4 | 230 | 12.74 |   12.74 |  30.69
    5 | 509 | 28.20 |   28.20 |  58.89
    6 |  70 |  3.88 |    3.88 |  62.77
    7 | 276 | 15.29 |   15.29 |  78.06
    8 | 138 |  7.65 |    7.65 |  85.71
    9 | 220 | 12.19 |   12.19 |  97.89
   10 |  38 |  2.11 |    2.11 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>m01 <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data<span class="sc">$</span>m01, <span class="st">"c(1,2,3,4,5)=1; c(6,7)=2; c(8,9,10)=3"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>m01 <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>m01,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Educacion Técnica Superior"</span>, <span class="st">"Educación Universitaria"</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> <span class="fu">rename</span>(proc_data,<span class="st">"educacion"</span><span class="ot">=</span>m01)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>educacion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>educacion <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>educacion,<span class="at">label =</span> <span class="st">"Educación"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>educacion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Educación (x) &lt;categorical&gt; 
# total N=1805 valid N=742 mean=1.53 sd=0.50

Value                      |    N | Raw % | Valid % | Cum. %
------------------------------------------------------------
Educacion Técnica Superior |  346 | 19.17 |   46.63 |  46.63
Educación Universitaria    |  396 | 21.94 |   53.37 | 100.00
&lt;NA&gt;                       | 1063 | 58.89 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Selección de muestra</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(educacion <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Educación Universitaria"</span>, <span class="st">"Educacion Técnica Superior"</span>))</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="do">##NSE</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>c33)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=742 valid N=742 mean=2.66 sd=0.74

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 |  38 |  5.12 |    5.12 |   5.12
    2 | 247 | 33.29 |   33.29 |  38.41
    3 | 392 | 52.83 |   52.83 |  91.24
    4 |  57 |  7.68 |    7.68 |  98.92
    5 |   8 |  1.08 |    1.08 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"NSE"</span><span class="ot">=</span>c33)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>NSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=742 valid N=742 mean=2.66 sd=0.74

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 |  38 |  5.12 |    5.12 |   5.12
    2 | 247 | 33.29 |   33.29 |  38.41
    3 | 392 | 52.83 |   52.83 |  91.24
    4 |  57 |  7.68 |    7.68 |  98.92
    5 |   8 |  1.08 |    1.08 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>NSE <span class="ot">&lt;-</span> <span class="fu">set_label</span>(proc_data<span class="sc">$</span>NSE, <span class="at">label =</span> <span class="st">"Nivel Socioeconómico"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>NSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Nivel Socioeconómico"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>NSE <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(proc_data<span class="sc">$</span>NSE <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="st">"NSE Bajo"</span>,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">ifelse</span>(proc_data<span class="sc">$</span>NSE <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>), <span class="st">"NSE Medio"</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">ifelse</span>(proc_data<span class="sc">$</span>NSE <span class="sc">==</span> <span class="dv">5</span>, <span class="st">"NSE Alto"</span>, <span class="cn">NA</span>)))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(proc_data<span class="sc">$</span>NSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Frequencies  
proc_data$NSE  
Type: Character  

                  Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
--------------- ------ --------- -------------- --------- --------------
       NSE Alto      8      1.08           1.08      1.08           1.08
       NSE Bajo    285     38.41          39.49     38.41          39.49
      NSE Medio    449     60.51         100.00     60.51         100.00
           &lt;NA&gt;      0                               0.00         100.00
          Total    742    100.00         100.00    100.00         100.00</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Sexo</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>m0_sexo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=742 valid N=742 mean=1.57 sd=0.50

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 | 319 | 42.99 |   42.99 |  42.99
    2 | 423 | 57.01 |   57.01 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>m0_sexo <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data<span class="sc">$</span>m0_sexo, <span class="st">"1=0;2=1"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>m0_sexo <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>m0_sexo,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Hombre"</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Mujer"</span>),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> <span class="fu">rename</span>(proc_data,<span class="st">"sexo"</span><span class="ot">=</span>m0_sexo)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>sexo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>sexo <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>sexo,<span class="at">label =</span> <span class="st">"Sexo"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>sexo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sexo (x) &lt;categorical&gt; 
# total N=742 valid N=742 mean=1.57 sd=0.50

Value  |   N | Raw % | Valid % | Cum. %
---------------------------------------
Hombre | 319 | 42.99 |   42.99 |  42.99
Mujer  | 423 | 57.01 |   57.01 | 100.00
&lt;NA&gt;   |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Edad</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>m0_edad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=742 valid N=742 mean=39.91 sd=14.47

Value |  N | Raw % | Valid % | Cum. %
-------------------------------------
   18 |  4 |  0.54 |    0.54 |   0.54
   19 | 12 |  1.62 |    1.62 |   2.16
   20 |  9 |  1.21 |    1.21 |   3.37
   21 | 23 |  3.10 |    3.10 |   6.47
   22 | 20 |  2.70 |    2.70 |   9.16
   23 | 20 |  2.70 |    2.70 |  11.86
   24 | 26 |  3.50 |    3.50 |  15.36
   25 | 18 |  2.43 |    2.43 |  17.79
   26 | 17 |  2.29 |    2.29 |  20.08
   27 | 21 |  2.83 |    2.83 |  22.91
   28 | 28 |  3.77 |    3.77 |  26.68
   29 | 21 |  2.83 |    2.83 |  29.51
   30 | 31 |  4.18 |    4.18 |  33.69
   31 | 21 |  2.83 |    2.83 |  36.52
   32 | 17 |  2.29 |    2.29 |  38.81
   33 | 19 |  2.56 |    2.56 |  41.37
   34 | 19 |  2.56 |    2.56 |  43.94
   35 | 21 |  2.83 |    2.83 |  46.77
   36 | 22 |  2.96 |    2.96 |  49.73
   37 | 10 |  1.35 |    1.35 |  51.08
   38 | 12 |  1.62 |    1.62 |  52.70
   39 | 11 |  1.48 |    1.48 |  54.18
   40 | 21 |  2.83 |    2.83 |  57.01
   41 | 16 |  2.16 |    2.16 |  59.16
   42 | 17 |  2.29 |    2.29 |  61.46
   43 | 12 |  1.62 |    1.62 |  63.07
   44 |  8 |  1.08 |    1.08 |  64.15
   45 | 11 |  1.48 |    1.48 |  65.63
   46 | 13 |  1.75 |    1.75 |  67.39
   47 |  8 |  1.08 |    1.08 |  68.46
   48 | 12 |  1.62 |    1.62 |  70.08
   49 | 13 |  1.75 |    1.75 |  71.83
   50 | 24 |  3.23 |    3.23 |  75.07
   51 | 12 |  1.62 |    1.62 |  76.68
   52 | 14 |  1.89 |    1.89 |  78.57
   53 | 14 |  1.89 |    1.89 |  80.46
   54 | 11 |  1.48 |    1.48 |  81.94
   55 | 12 |  1.62 |    1.62 |  83.56
   56 | 16 |  2.16 |    2.16 |  85.71
   57 | 10 |  1.35 |    1.35 |  87.06
   58 |  7 |  0.94 |    0.94 |  88.01
   59 |  7 |  0.94 |    0.94 |  88.95
   60 |  7 |  0.94 |    0.94 |  89.89
   61 |  4 |  0.54 |    0.54 |  90.43
   62 |  5 |  0.67 |    0.67 |  91.11
   63 |  4 |  0.54 |    0.54 |  91.64
   64 |  7 |  0.94 |    0.94 |  92.59
   65 |  9 |  1.21 |    1.21 |  93.80
   66 |  3 |  0.40 |    0.40 |  94.20
   67 |  7 |  0.94 |    0.94 |  95.15
   68 |  8 |  1.08 |    1.08 |  96.23
   69 |  1 |  0.13 |    0.13 |  96.36
   70 |  3 |  0.40 |    0.40 |  96.77
   71 |  2 |  0.27 |    0.27 |  97.04
   72 |  6 |  0.81 |    0.81 |  97.84
   73 |  4 |  0.54 |    0.54 |  98.38
   74 |  4 |  0.54 |    0.54 |  98.92
   75 |  6 |  0.81 |    0.81 |  99.73
   77 |  1 |  0.13 |    0.13 |  99.87
   78 |  1 |  0.13 |    0.13 | 100.00
 &lt;NA&gt; |  0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> <span class="fu">rename</span>(proc_data,<span class="st">"edad"</span><span class="ot">=</span>m0_edad)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>edad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>edad <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>edad,<span class="at">label =</span> <span class="st">"Edad"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>edad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Edad (x) &lt;numeric&gt; 
# total N=742 valid N=742 mean=39.91 sd=14.47

Value |  N | Raw % | Valid % | Cum. %
-------------------------------------
   18 |  4 |  0.54 |    0.54 |   0.54
   19 | 12 |  1.62 |    1.62 |   2.16
   20 |  9 |  1.21 |    1.21 |   3.37
   21 | 23 |  3.10 |    3.10 |   6.47
   22 | 20 |  2.70 |    2.70 |   9.16
   23 | 20 |  2.70 |    2.70 |  11.86
   24 | 26 |  3.50 |    3.50 |  15.36
   25 | 18 |  2.43 |    2.43 |  17.79
   26 | 17 |  2.29 |    2.29 |  20.08
   27 | 21 |  2.83 |    2.83 |  22.91
   28 | 28 |  3.77 |    3.77 |  26.68
   29 | 21 |  2.83 |    2.83 |  29.51
   30 | 31 |  4.18 |    4.18 |  33.69
   31 | 21 |  2.83 |    2.83 |  36.52
   32 | 17 |  2.29 |    2.29 |  38.81
   33 | 19 |  2.56 |    2.56 |  41.37
   34 | 19 |  2.56 |    2.56 |  43.94
   35 | 21 |  2.83 |    2.83 |  46.77
   36 | 22 |  2.96 |    2.96 |  49.73
   37 | 10 |  1.35 |    1.35 |  51.08
   38 | 12 |  1.62 |    1.62 |  52.70
   39 | 11 |  1.48 |    1.48 |  54.18
   40 | 21 |  2.83 |    2.83 |  57.01
   41 | 16 |  2.16 |    2.16 |  59.16
   42 | 17 |  2.29 |    2.29 |  61.46
   43 | 12 |  1.62 |    1.62 |  63.07
   44 |  8 |  1.08 |    1.08 |  64.15
   45 | 11 |  1.48 |    1.48 |  65.63
   46 | 13 |  1.75 |    1.75 |  67.39
   47 |  8 |  1.08 |    1.08 |  68.46
   48 | 12 |  1.62 |    1.62 |  70.08
   49 | 13 |  1.75 |    1.75 |  71.83
   50 | 24 |  3.23 |    3.23 |  75.07
   51 | 12 |  1.62 |    1.62 |  76.68
   52 | 14 |  1.89 |    1.89 |  78.57
   53 | 14 |  1.89 |    1.89 |  80.46
   54 | 11 |  1.48 |    1.48 |  81.94
   55 | 12 |  1.62 |    1.62 |  83.56
   56 | 16 |  2.16 |    2.16 |  85.71
   57 | 10 |  1.35 |    1.35 |  87.06
   58 |  7 |  0.94 |    0.94 |  88.01
   59 |  7 |  0.94 |    0.94 |  88.95
   60 |  7 |  0.94 |    0.94 |  89.89
   61 |  4 |  0.54 |    0.54 |  90.43
   62 |  5 |  0.67 |    0.67 |  91.11
   63 |  4 |  0.54 |    0.54 |  91.64
   64 |  7 |  0.94 |    0.94 |  92.59
   65 |  9 |  1.21 |    1.21 |  93.80
   66 |  3 |  0.40 |    0.40 |  94.20
   67 |  7 |  0.94 |    0.94 |  95.15
   68 |  8 |  1.08 |    1.08 |  96.23
   69 |  1 |  0.13 |    0.13 |  96.36
   70 |  3 |  0.40 |    0.40 |  96.77
   71 |  2 |  0.27 |    0.27 |  97.04
   72 |  6 |  0.81 |    0.81 |  97.84
   73 |  4 |  0.54 |    0.54 |  98.38
   74 |  4 |  0.54 |    0.54 |  98.92
   75 |  6 |  0.81 |    0.81 |  99.73
   77 |  1 |  0.13 |    0.13 |  99.87
   78 |  1 |  0.13 |    0.13 | 100.00
 &lt;NA&gt; |  0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Participación Política</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"apoyo_causa"</span><span class="ot">=</span>c08_01,  </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"part_marcha"</span><span class="ot">=</span>c08_02, </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"part_huelga"</span><span class="ot">=</span>c08_03, </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"rrss_pol"</span><span class="ot">=</span>c08_04)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>apoyo_causa <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>apoyo_causa,<span class="at">label =</span> <span class="st">"Participación: Apoya Causa"</span>)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>apoyo_causa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Participación: Apoya Causa"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>part_marcha <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>part_marcha, <span class="at">label =</span> <span class="st">"Participación: Marcha"</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>part_marcha)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Participación: Marcha"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>part_huelga <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>part_huelga, <span class="at">label =</span> <span class="st">"Participación: Huelga"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>part_huelga)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Participación: Huelga"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>rrss_pol <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>rrss_pol, <span class="at">label =</span> <span class="st">"Participación: RRSS"</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>rrss_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Participación: RRSS"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>apoyo_causa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Participación: Apoya Causa (x) &lt;numeric&gt; 
# total N=742 valid N=742 mean=1.90 sd=1.06

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 | 385 | 51.89 |   51.89 |  51.89
    2 | 106 | 14.29 |   14.29 |  66.17
    3 | 197 | 26.55 |   26.55 |  92.72
    4 |  45 |  6.06 |    6.06 |  98.79
    5 |   9 |  1.21 |    1.21 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>part_marcha)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Participación: Marcha (x) &lt;numeric&gt; 
# total N=742 valid N=742 mean=1.64 sd=1.01

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 | 494 | 66.58 |   66.58 |  66.58
    2 |  74 |  9.97 |    9.97 |  76.55
    3 | 128 | 17.25 |   17.25 |  93.80
    4 |  36 |  4.85 |    4.85 |  98.65
    5 |  10 |  1.35 |    1.35 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>part_huelga)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Participación: Huelga (x) &lt;numeric&gt; 
# total N=742 valid N=742 mean=1.37 sd=0.83

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 | 602 | 81.13 |   81.13 |  81.13
    2 |  36 |  4.85 |    4.85 |  85.98
    3 |  77 | 10.38 |   10.38 |  96.36
    4 |  23 |  3.10 |    3.10 |  99.46
    5 |   4 |  0.54 |    0.54 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>rrss_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Participación: RRSS (x) &lt;numeric&gt; 
# total N=742 valid N=742 mean=2.31 sd=1.39

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 | 347 | 46.77 |   46.77 |  46.77
    2 |  55 |  7.41 |    7.41 |  54.18
    3 | 159 | 21.43 |   21.43 |  75.61
    4 | 125 | 16.85 |   16.85 |  92.45
    5 |  56 |  7.55 |    7.55 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>apoyo_causa <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>apoyo_causa,</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Poco"</span>, <span class="st">"Poco"</span>, <span class="st">"Algo"</span>, <span class="st">"Mucha"</span>, <span class="st">"Mucha"</span>))</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>part_marcha <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>part_marcha,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Poco"</span>, <span class="st">"Poco"</span>, <span class="st">"Algo"</span>, <span class="st">"Mucha"</span>, <span class="st">"Mucha"</span>))</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>part_huelga <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>part_huelga,</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Poco"</span>, <span class="st">"Poco"</span>, <span class="st">"Algo"</span>, <span class="st">"Mucha"</span>, <span class="st">"Mucha"</span>))</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>rrss_pol <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>rrss_pol,</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Poco"</span>, <span class="st">"Poco"</span>, <span class="st">"Algo"</span>, <span class="st">"Mucha"</span>, <span class="st">"Mucha"</span>))</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a><span class="do">##Membresías</span></span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"pert_jdv"</span><span class="ot">=</span>c12_01,  </span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"pert_pp"</span><span class="ot">=</span>c12_03, </span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"pert_cde"</span><span class="ot">=</span>c12_08)</span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-21"><a href="#cb49-21" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>pert_jdv <span class="ot">&lt;-</span> <span class="fu">set_label</span>(proc_data<span class="sc">$</span>pert_jdv, <span class="at">label =</span> <span class="st">"Pertenece: Junta de vecinos"</span>)</span>
<span id="cb49-22"><a href="#cb49-22" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>pert_jdv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Pertenece: Junta de vecinos"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>pert_pp <span class="ot">&lt;-</span> <span class="fu">set_label</span>(proc_data<span class="sc">$</span>pert_pp, <span class="at">label =</span> <span class="st">"Pertenece: Partido Político"</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>pert_pp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Pertenece: Partido Político"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>pert_cde <span class="ot">&lt;-</span> <span class="fu">set_label</span>(proc_data<span class="sc">$</span>pert_cde, <span class="at">label =</span> <span class="st">"Pertenece: Centro de estudiantes"</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>pert_cde)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Pertenece: Centro de estudiantes"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>pert_jdv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pertenece: Junta de vecinos (x) &lt;numeric&gt; 
# total N=742 valid N=742 mean=1.40 sd=0.73

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 | 557 | 75.07 |   75.07 |  75.07
    2 |  75 | 10.11 |   10.11 |  85.18
    3 | 110 | 14.82 |   14.82 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>pert_pp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pertenece: Partido Político (x) &lt;numeric&gt; 
# total N=742 valid N=742 mean=1.10 sd=0.38

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 | 688 | 92.72 |   92.72 |  92.72
    2 |  33 |  4.45 |    4.45 |  97.17
    3 |  21 |  2.83 |    2.83 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>pert_cde)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pertenece: Centro de estudiantes (x) &lt;numeric&gt; 
# total N=742 valid N=742 mean=1.13 sd=0.45

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 | 683 | 92.05 |   92.05 |  92.05
    2 |  25 |  3.37 |    3.37 |  95.42
    3 |  34 |  4.58 |    4.58 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>pert_jdv <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>pert_jdv,</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Si"</span>, <span class="st">"Si"</span>))</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>pert_pp <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>pert_pp,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Si"</span>, <span class="st">"Si"</span>))</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>pert_cde <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>pert_cde,</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>                             <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Si"</span>, <span class="st">"Si"</span>))</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a><span class="do">##Interés en la política</span></span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"interes_pol"</span><span class="ot">=</span>c13)</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>interes_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=742 valid N=742 mean=2.24 sd=1.29

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 | 304 | 40.97 |   40.97 |  40.97
    2 | 148 | 19.95 |   19.95 |  60.92
    3 | 144 | 19.41 |   19.41 |  80.32
    4 |  99 | 13.34 |   13.34 |  93.67
    5 |  47 |  6.33 |    6.33 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>interes_pol <span class="ot">&lt;-</span> <span class="fu">set_label</span>(proc_data<span class="sc">$</span>interes_pol, <span class="at">label =</span> <span class="st">"Interés Político"</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>interes_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Interés Político"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>interes_pol <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>interes_pol,</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Sin interés"</span>, <span class="st">"Poco interés"</span>, <span class="st">"Poco interés"</span>, <span class="st">"Alto interés"</span>, <span class="st">"Alto interés"</span>))</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="do">##Autoubicación Política</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"autoubic_pol"</span><span class="ot">=</span>c15)</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>autoubic_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=742 valid N=742 mean=6.77 sd=3.74

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    0 |  33 |  4.45 |    4.45 |   4.45
    1 |  14 |  1.89 |    1.89 |   6.33
    2 |  42 |  5.66 |    5.66 |  11.99
    3 |  47 |  6.33 |    6.33 |  18.33
    4 |  62 |  8.36 |    8.36 |  26.68
    5 | 183 | 24.66 |   24.66 |  51.35
    6 |  40 |  5.39 |    5.39 |  56.74
    7 |  44 |  5.93 |    5.93 |  62.67
    8 |  29 |  3.91 |    3.91 |  66.58
    9 |   5 |  0.67 |    0.67 |  67.25
   10 |  40 |  5.39 |    5.39 |  72.64
   11 |  39 |  5.26 |    5.26 |  77.90
   12 | 164 | 22.10 |   22.10 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>autoubic_pol <span class="ot">&lt;-</span> <span class="fu">set_label</span>(proc_data<span class="sc">$</span>autoubic_pol, <span class="at">label =</span> <span class="st">"Ubicación Política"</span>)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>autoubic_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Ubicación Política"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>autoubic_pol <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data<span class="sc">$</span>autoubic_pol, <span class="st">"c(0,1,2,3)=1; c(4,5,6)=2; c(7,8,9,10)=3; c(11,12)=4"</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>autoubic_pol <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>autoubic_pol,</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Izquierda"</span>, <span class="st">"Centro"</span>, <span class="st">"Educacion superior"</span>, <span class="st">"Ninguna"</span>),</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>))</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a><span class="do">##Participación en Movimientos Sociales</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"part_movsoc"</span><span class="ot">=</span>c22)</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>part_movsoc <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>part_movsoc,<span class="at">label =</span> <span class="st">"Participación: Movimientos Sociales"</span>)</span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>part_movsoc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Participación: Movimientos Sociales"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>part_movsoc <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data<span class="sc">$</span>part_movsoc,</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>                             <span class="st">"1:2 = 1;</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="st">                              3 = 2;</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="st">                              4:5 = 3"</span>)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>part_movsoc <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>part_movsoc,</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Baja"</span>, <span class="st">"Alta"</span>),</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>part_movsoc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=742 valid N=659 mean=1.23 sd=0.42

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
Baja  | 506 | 68.19 |   76.78 |  76.78
Alta  | 153 | 20.62 |   23.22 | 100.00
&lt;NA&gt;  |  83 | 11.19 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
</section>
<section id="descriptivos" class="level2">
<h2 class="anchored" data-anchor-id="descriptivos">Descriptivos</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(proc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 742  14</code></pre>
</div>
</div>
<div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">descr</span>(proc_data)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">descr</span>(proc_data,</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">show =</span> <span class="fu">c</span>(<span class="st">"label"</span>,<span class="st">"range"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"NA.prc"</span>, <span class="st">"n"</span>))<span class="sc">%&gt;%</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(.,<span class="st">"markdown"</span>)</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>summarytools<span class="sc">::</span><span class="fu">dfSummary</span>(proc_data, <span class="at">plain.ascii =</span> <span class="cn">FALSE</span>)</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(<span class="fu">dfSummary</span>(proc_data, <span class="at">headings=</span><span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Switching method to 'browser'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Output file written: C:\Users\sivim\AppData\Local\Temp\RtmpMxl3pq\file2bdc159ccbf.html</code></pre>
</div>
<div id="tbl-sjmisc" class="cell tbl-parent quarto-layout-panel anchored">
<div class="panel-caption table-caption">
<p><strong>?(caption)</strong></p>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<pre><code>
## Basic descriptive statistics

          var        type        label   n NA.prc  mean    sd   se md trimmed
         sexo categorical         Sexo 742   0.00  1.57  0.50 0.02  2    1.59
         edad     numeric         Edad 742   0.00 39.91 14.47 0.53 37   38.79
    educacion categorical    Educación 742   0.00  1.53  0.50 0.02  2    1.54
  apoyo_causa categorical  apoyo_causa 742   0.00  1.41  0.62 0.02  1    1.30
  part_marcha categorical  part_marcha 742   0.00  1.30  0.58 0.02  1    1.17
  part_huelga categorical  part_huelga 742   0.00  1.18  0.47 0.02  1    1.05
     rrss_pol categorical     rrss_pol 742   0.00  1.70  0.84 0.03  1    1.63
     pert_jdv categorical     pert_jdv 742   0.00  1.25  0.43 0.02  1    1.19
      pert_pp categorical      pert_pp 742   0.00  1.07  0.26 0.01  1    1.00
     pert_cde categorical     pert_cde 742   0.00  1.08  0.27 0.01  1    1.00
  interes_pol categorical  interes_pol 742   0.00  1.79  0.75 0.03  2    1.73
 autoubic_pol categorical autoubic_pol 742   0.00  2.52  1.08 0.04  2    2.53
  part_movsoc categorical  part_movsoc 659  11.19  1.23  0.42 0.02  1    1.17
      range iqr  skew
    1 (1-2)   1 -0.28
 60 (18-78)  22  0.56
    1 (1-2)   1 -0.14
    2 (1-3)   1  1.25
    2 (1-3)   0  1.81
    2 (1-3)   0  2.69
    2 (1-3)   1  0.61
    1 (1-2)   0  1.16
    1 (1-2)   0  3.30
    1 (1-2)   0  3.11
    2 (1-3)   1  0.37
    3 (1-4)   2  0.16
    1 (1-2)   0  1.27</code></pre>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">var</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">NA.prc</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: left;">range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">sexo</td>
<td style="text-align: left;">Sexo</td>
<td style="text-align: right;">742</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.570081</td>
<td style="text-align: right;">0.4953983</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">edad</td>
<td style="text-align: left;">Edad</td>
<td style="text-align: right;">742</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">39.913747</td>
<td style="text-align: right;">14.4691248</td>
<td style="text-align: left;">60 (18-78)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">educacion</td>
<td style="text-align: left;">Educación</td>
<td style="text-align: right;">742</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.533693</td>
<td style="text-align: right;">0.4992000</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">apoyo_causa</td>
<td style="text-align: left;">apoyo_causa</td>
<td style="text-align: right;">742</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.411051</td>
<td style="text-align: right;">0.6230279</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">part_marcha</td>
<td style="text-align: left;">part_marcha</td>
<td style="text-align: right;">742</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.296496</td>
<td style="text-align: right;">0.5770824</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">part_huelga</td>
<td style="text-align: left;">part_huelga</td>
<td style="text-align: right;">742</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.176550</td>
<td style="text-align: right;">0.4673871</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12</td>
<td style="text-align: left;">rrss_pol</td>
<td style="text-align: left;">rrss_pol</td>
<td style="text-align: right;">742</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.702156</td>
<td style="text-align: right;">0.8354305</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">pert_jdv</td>
<td style="text-align: left;">pert_jdv</td>
<td style="text-align: right;">742</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.249326</td>
<td style="text-align: right;">0.4329148</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">pert_pp</td>
<td style="text-align: left;">pert_pp</td>
<td style="text-align: right;">742</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.072776</td>
<td style="text-align: right;">0.2599441</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: left;">pert_cde</td>
<td style="text-align: left;">pert_cde</td>
<td style="text-align: right;">742</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.079515</td>
<td style="text-align: right;">0.2707231</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">interes_pol</td>
<td style="text-align: left;">interes_pol</td>
<td style="text-align: right;">742</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.787062</td>
<td style="text-align: right;">0.7495890</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">autoubic_pol</td>
<td style="text-align: left;">autoubic_pol</td>
<td style="text-align: right;">742</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">2.522911</td>
<td style="text-align: right;">1.0792551</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: left;">part_movsoc</td>
<td style="text-align: left;">part_movsoc</td>
<td style="text-align: right;">659</td>
<td style="text-align: right;">11.18598</td>
<td style="text-align: right;">1.232170</td>
<td style="text-align: right;">0.4225376</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<pre><code>### Data Frame Summary  
#### proc_data  
**Label:** Estudio Longitudinal Social de Chile. Ola 2016. Version 4.00 (10/06/2020)  
**Dimensions:** 742 x 14  
**Duplicates:** 8  

-----------------------------------------------------------------------------------------------------------------------------------
No   Variable        Label       Stats / Values                   Freqs (% of Valid)   Graph                   Valid      Missing  
---- --------------- ----------- -------------------------------- -------------------- ----------------------- ---------- ---------
1    sexo\           Sexo        1\. Hombre\                      319 (43.0%)\         IIIIIIII \              742\       0\       
     [factor]                    2\. Mujer                        423 (57.0%)          IIIIIIIIIII             (100.0%)   (0.0%)   

2    edad\           Edad        Mean (sd) : 39.9 (14.5)\         60 distinct values   \ \ : .\                742\       0\       
     [numeric]                   min &lt; med &lt; max:\                                     : : :\                  (100.0%)   (0.0%)   
                                 18 &lt; 37 &lt; 78\                                         : : : : . :\                                
                                 IQR (CV) : 22 (0.4)                                   : : : : : : :\                              
                                                                                       : : : : : : : : : .                         

3    educacion\      Educación   1\. Educacion Técnica Superio\   346 (46.6%)\         IIIIIIIII \             742\       0\       
     [factor]                    2\. Educación Universitaria      396 (53.4%)          IIIIIIIIII              (100.0%)   (0.0%)   

4    apoyo_causa\                1\. Poco\                        491 (66.2%)\         IIIIIIIIIIIII \         742\       0\       
     [factor]                    2\. Algo\                        197 (26.5%)\         IIIII \                 (100.0%)   (0.0%)   
                                 3\. Mucha                        54 ( 7.3%)           I                                           

5    part_marcha\                1\. Poco\                        568 (76.5%)\         IIIIIIIIIIIIIII \       742\       0\       
     [factor]                    2\. Algo\                        128 (17.3%)\         III \                   (100.0%)   (0.0%)   
                                 3\. Mucha                        46 ( 6.2%)           I                                           

6    part_huelga\                1\. Poco\                        638 (86.0%)\         IIIIIIIIIIIIIIIII \     742\       0\       
     [factor]                    2\. Algo\                        77 (10.4%)\          II \                    (100.0%)   (0.0%)   
                                 3\. Mucha                        27 ( 3.6%)                                                       

7    rrss_pol\                   1\. Poco\                        402 (54.2%)\         IIIIIIIIII \            742\       0\       
     [factor]                    2\. Algo\                        159 (21.4%)\         IIII \                  (100.0%)   (0.0%)   
                                 3\. Mucha                        181 (24.4%)          IIII                                        

8    pert_jdv\                   1\. No\                          557 (75.1%)\         IIIIIIIIIIIIIII \       742\       0\       
     [factor]                    2\. Si                           185 (24.9%)          IIII                    (100.0%)   (0.0%)   

9    pert_pp\                    1\. No\                          688 (92.7%)\         IIIIIIIIIIIIIIIIII \    742\       0\       
     [factor]                    2\. Si                           54 ( 7.3%)           I                       (100.0%)   (0.0%)   

10   pert_cde\                   1\. No\                          683 (92.0%)\         IIIIIIIIIIIIIIIIII \    742\       0\       
     [factor]                    2\. Si                           59 ( 8.0%)           I                       (100.0%)   (0.0%)   

11   interes_pol\                1\. Sin interés\                 304 (41.0%)\         IIIIIIII \              742\       0\       
     [factor]                    2\. Poco interés\                292 (39.4%)\         IIIIIII \               (100.0%)   (0.0%)   
                                 3\. Alto interés                 146 (19.7%)          III                                         

12   autoubic_pol\               1\. Izquierda\                   136 (18.3%)\         III \                   742\       0\       
     [factor]                    2\. Centro\                      285 (38.4%)\         IIIIIII \               (100.0%)   (0.0%)   
                                 3\. Educacion superior\          118 (15.9%)\         III \                                       
                                 4\. Ninguna                      203 (27.4%)          IIIII                                       

13   part_movsoc\                1\. Baja\                        506 (76.8%)\         IIIIIIIIIIIIIII \       659\       83\      
     [factor]                    2\. Alta                         153 (23.2%)          IIII                    (88.8%)    (11.2%)  

14   NSE\                        1\. NSE Alto\                    8 ( 1.1%)\           \                       742\       0\       
     [character]                 2\. NSE Bajo\                    285 (38.4%)\         IIIIIII \               (100.0%)   (0.0%)   
                                 3\. NSE Medio                    449 (60.5%)          IIIIIIIIIIII                                
-----------------------------------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
</div>
</div>
<p>Como se observa en la tabla, la muestra final está compuesta en un 43% por hombres y un 57% de mujeres. El promedio de edad es de 39,9 años, con una desviación estándar de 14,5 años. La distribución de la muestra es bastante amplia, abarcando desde los 18 a los 78 años. Podemos ver que la mayoría de estudiantes seleccionados tienen educación universitaria (53,4%), en comparación a la educación técnica superior que es del 46,6%. En el resto de variables que abarcan participación política, la mayoría de los estudiantes reportan poco apoyo a causas (66.2%), poca participación en marchas (76.5%), poca participación en huelgas (86.0%), y poco uso de redes sociales para fines políticos (54.2%). Respecto a la pertenencia, la mayoría de los estudiantes no son miembros de juntas de vecinos (75.1%), partidos políticos (92.7%), ni centros de estudiantes (92.0%). Alrededor del 41.0% de los estudiantes reportan poco interés político, mientras que el 39.4% reporta algo de interés y el 19.7% reporta alto interés. La mayoría de los estudiantes se ubican en el centro político (38.4%) o no se ubican en ninguna posición política específica (27.4%). La mayoría de los estudiantes reportan una participación baja en movimientos sociales (76.8%). Finalmente, la mayoría de los estudiantes ienen un nivel socioeconómico medio (60.5%), seguido por un 38.4% con nivel socioeconómico bajo y solo un pequeño porcentaje (1.1%) con nivel socioeconómico alto.</p>
</section>
<section id="gráficos-univariados" class="level2">
<h2 class="anchored" data-anchor-id="gráficos-univariados">Gráficos Univariados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráficos univariados.</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-gdp</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: “Educacion e Interés político”</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>graph1 <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> interes_pol, <span class="at">fill =</span> educacion)) <span class="sc">+</span> </span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Interés Político"</span>) <span class="sc">+</span></span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Educación"</span>) <span class="sc">+</span> </span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill=</span><span class="st">"educacion"</span>)<span class="sc">+</span></span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Universitario'</span>,<span class="st">'Tecnico Superior'</span>))</span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a>graph1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="desigualdad-pp2_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En este gráfico podemos observar que quieres menos presentan interés político son los estudiantes universitarios, y quienes presentan un alto interés son los estudiantes de educación técnico superior.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráficos univariados.</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-gdp</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: “Educacion, Interés político y NSE”</span></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>graph2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(proc_data, <span class="fu">aes</span>(<span class="at">x =</span> NSE, <span class="at">fill =</span> educacion)) <span class="sc">+</span></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> interes_pol) <span class="sc">+</span></span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"NSE"</span>, <span class="at">y =</span> <span class="st">"Proporción"</span>, <span class="at">fill =</span> <span class="st">"Nivel educacional"</span>) <span class="sc">+</span></span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>graph2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="desigualdad-pp2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Al incluir la variable de nivel socioeconómico en el análisis, se observa que los estudiantes de educación universitaria con un NSE medio muestran el mayor interés político, mientras que los estudiantes de educación técnica superior con un NSE bajo muestran el menor interés político. Esto sugiere que el nivel socioeconómico puede influir en el grado de interés político de los estudiantes, independientemente de su nivel educativo.</p>
<p>El estudio sobre las tendencias de desigualdad y participación política entre estudiantes universitarios en Chile destaca la compleja interacción entre factores sociales, económicos y educativos en la configuración de actitudes políticas y comportamientos cívicos. La desigualdad social y económica en Chile no solo afecta la calidad de vida de los ciudadanos, sino que también influye en su participación política y en la percepción de las instituciones democráticas.</p>
<p>La educación cívica emerge como una herramienta esencial para abordar estas desigualdades y fomentar la participación ciudadana informada. Sin embargo, el estudio sugiere que el nivel socioeconómico también desempeña un papel significativo en el grado de interés político de los estudiantes, lo que subraya la importancia de considerar el contexto socioeconómico al analizar la participación política de los jóvenes.</p>
<p>La hipótesis planteada en el estudio, que sugiere que una mayor percepción de la desigualdad social entre los estudiantes universitarios se relaciona con una mayor participación política, abre nuevas vías de investigación sobre cómo los jóvenes responden a las disparidades socioeconómicas y buscan influir en el cambio social y económico a través de la acción política.</p>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-castilloSocialInequalityChanges2014" class="csl-entry" role="listitem">
Castillo, Juan C, Daniel Miranda, Macarena Bonhomme, Cristián Cox, and Martín Bascopé. 2014. <span>“Social Inequality and Changes in Students’ Expected Political Participation in <span>Chile</span>.”</span> <em>Education, Citizenship and Social Justice</em> 9 (2): 140–56. <a href="https://doi.org/10.1177/1746197914520650">https://doi.org/10.1177/1746197914520650</a>.
</div>
<div id="ref-diegocolladoEffectsClassroomSocioeconomic2015" class="csl-entry" role="listitem">
Diego Collado, Diego Collado, Catalina Lomos, Catalina Lomos, Idès Nicaise, and Ides Nicaise. 2015. <span>“The Effects of Classroom Socioeconomic Composition on Student’s Civic Knowledge in <span>Chile</span>.”</span> <em>School Effectiveness and School Improvement</em> 26 (3): 415–40. <a href="https://doi.org/10.1080/09243453.2014.966725">https://doi.org/10.1080/09243453.2014.966725</a>.
</div>
<div id="ref-juancarloscastilloMitigatingPoliticalParticipation2015" class="csl-entry" role="listitem">
Juan Carlos Castillo, Juan Carlos Castillo, Daniel Miranda, Daniel Miranda, Macarena Bonhomme, Macarena Bonhomme, Cristián Cox, Cristián Cox, Martín Bascopé, and Martín Bascopé. 2015. <span>“Mitigating the Political Participation Gap from the School: The Roles of Civic Knowledge and Classroom Climate.”</span> <em>Journal of Youth Studies</em> 18 (1): 16–35. <a href="https://doi.org/10.1080/13676261.2014.933199">https://doi.org/10.1080/13676261.2014.933199</a>.
</div>
<div id="ref-marchoogheVotersCandidatesFuture2013" class="csl-entry" role="listitem">
Marc Hooghe, Ruth Dassonneville, Ruth Dassonneville, and Marc Hooghe. 2013. <span>“Voters and <span>Candidates</span> of the <span>Future</span>: <span>The Intention</span> of <span>Electoral Participation</span> Among <span>Adolescents</span> in 22 <span>European Countries</span>:”</span> 21 (1): 1–28. <a href="https://doi.org/10.1177/1103308812467664">https://doi.org/10.1177/1103308812467664</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>