<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sivonney Lillo Godoy">

<title>Desigualdad y Participación Política</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="desigualdad-pp3_files/libs/clipboard/clipboard.min.js"></script>
<script src="desigualdad-pp3_files/libs/quarto-html/quarto.js"></script>
<script src="desigualdad-pp3_files/libs/quarto-html/popper.min.js"></script>
<script src="desigualdad-pp3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="desigualdad-pp3_files/libs/quarto-html/anchor.min.js"></script>
<link href="desigualdad-pp3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="desigualdad-pp3_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="desigualdad-pp3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="desigualdad-pp3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="desigualdad-pp3_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Desigualdad y Participación Política</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sivonney Lillo Godoy </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="desigualdad-y-participación-política-en-chile" class="level1">
<h1>“Desigualdad y Participación Política en Chile”</h1>
<p>En el Chile actual, la desigualdad social y la estratificación económica han emergido como temas de alta relevancia sociológica, planteando desafíos significativos para la cohesión social y la justicia distributiva en las sociedades contemporáneas. La percepción de la desigualdad juega un papel crucial en la configuración de actitudes y comportamientos sociales y políticos de los individuos, y su impacto se refleja de manera notable en la participación política de la población.</p>
<p>La educación cívica y la política educativa se presentan como herramientas fundamentales para abordar esta problemática, ya que contribuyen a la formación de ciudadanos informados y comprometidos con el bienestar colectivo.</p>
<p>En este estudio, se propone analizar cómo la percepción de la desigualdad social influye en la participación política de los ciudadanos en Chile. Diversas investigaciones indican que la participación política está estrechamente relacionada con el estatus socioeconómico, siendo aquellos con un nivel socioeconómico más alto más propensos a involucrarse en el sistema político.<span class="citation" data-cites="castilloSocialInequalityChanges2014">(<a href="#ref-castilloSocialInequalityChanges2014" role="doc-biblioref">Castillo et al. 2014</a>)</span> La desigualdad social en Chile ha sido un tema recurrente que ha generado tensiones y debates en la sociedad, contribuyendo a la fragmentación social y a la percepción de injusticia entre diferentes estratos de la población. Esta disparidad socioeconómica no solo ha impactado en la calidad de vida de los ciudadanos, sino también en su participación política y en la legitimidad de las instituciones democráticas.</p>
<p>Además, en la literatura existe una creciente preocupación por las menores tasas de participación electoral entre las cohortes de edad más joven. Por ejemplo, un estudio <span class="citation" data-cites="marchoogheVotersCandidatesFuture2013">(<a href="#ref-marchoogheVotersCandidatesFuture2013" role="doc-biblioref">Marc Hooghe et al. 2013</a>)</span> investigó la disposición a votar entre adolescentes de 14 años de 22 países europeos y encontró que, si bien la disposición a votar sigue siendo elevada en este grupo de edad, existe una clara división de género. Las niñas son más propensas a afirmar que votarán, mientras que los niños se ven más a sí mismos como futuros candidatos electorales. Un clima de aula abierta en la escuela contribuye a la voluntad de votar en futuras elecciones. Sin embargo, elementos que impactan en la participación de adultos no tienen un efecto significativo en la intención de votar entre adolescentes, lo que sugiere que la menor tasa de participación observada entre los más jóvenes no puede atribuirse simplemente a una falta de motivación política, sino que deben considerarse otros elementos para explicar esta tendencia a la baja.</p>
<p>“La evidencia empírica ha demostrado consistentemente que la participación política está relacionada positivamente con el entorno socioeconómico. Además, investigaciones recientes sugieren que los niños que provienen de familias de bajo estatus ya están menos dispuestos a involucrarse políticamente.” <span class="citation" data-cites="juancarloscastilloMitigatingPoliticalParticipation2015">(<a href="#ref-juancarloscastilloMitigatingPoliticalParticipation2015" role="doc-biblioref">Juan Carlos Castillo et al. 2015</a>)</span></p>
<p>Ligado a lo anterior, las influencias positivas de condiciones socioeconómicas más favorables representan un aumento del 36% en los puntajes de las pruebas escolares. Estos hallazgos sugieren que en el sistema educativo chileno, caracterizado por su segregación socioeconómica, estos efectos podrían contribuir a ampliar la brecha en el rendimiento académico en el ámbito de la educación cívica entre los estudiantes de escuelas con mayores recursos y aquellos con menos recursos. Además, este estudio revela que, en promedio, los estudiantes con un estatus socioeconómico más elevado son más susceptibles a estas influencias, y que los efectos de la composición socioeconómica son más pronunciados en el sector privado subvencionado que en el sector público. <span class="citation" data-cites="diegocolladoEffectsClassroomSocioeconomic2015">(<a href="#ref-diegocolladoEffectsClassroomSocioeconomic2015" role="doc-biblioref">Diego Collado et al. 2015</a>)</span></p>
<p>En ese sentido, la hipótesis central que orientará esta investigación es que a medida que aumenta el nivel de percepción de la desigualdad social, también aumenta su participación política. Se espera que la percepción de la desigualdad social actúe como un predictor principal de la participación política de los chilenos, motivándolos a comprometerse activamente en la esfera política para abogar por cambios sociales y económicos.</p>
<p>Para efectos de este trabajo, utilizaré datos obtenidos a través del Estudio Longuitudinal de Chile (ELSOC_ola2016), con el fin de observar como se comporta la participación política en Chile.</p>
</section>
<section id="trabajo-en-r" class="level1">
<h1>Trabajo en R</h1>
<section id="ajustes-iniciales" class="level2">
<h2 class="anchored" data-anchor-id="ajustes-iniciales">Ajustes Iniciales</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Ajustes Iniciales</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cargar-paquetes" class="level2">
<h2 class="anchored" data-anchor-id="cargar-paquetes">Cargar Paquetes</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sjlabelled,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>               dplyr, <span class="co"># Manipulacion de datos</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>               stargazer, <span class="co"># Tablas</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>               sjmisc, <span class="co"># Tablas</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>               summarytools, <span class="co"># Tablas</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>               kableExtra, <span class="co"># Tablas</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>               sjPlot, <span class="co"># Tablas y gráficos</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>               corrplot, <span class="co"># Correlaciones</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>               sessioninfo, <span class="co"># Información de la sesión de trabajo</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>               ggplot2, <span class="co"># Para la mayoría de los gráficos</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>               GGally,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>               car,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>               texreg,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>               sjlabelled, </span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>               fastDummies, </span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>               ggeffects)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cargar-base-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="cargar-base-de-datos">Cargar Base de Datos</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"Input/data original/ELSOC_W01_v4.01_R.RData"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(elsoc_2016)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(elsoc_2016)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "idencuesta"      "ola"             "version"         "muestra"        
  [5] "cuestion_mig"    "t01"             "t02_01"          "t02_02"         
  [9] "t02_03"          "t02_04"          "t03_01"          "t03_02"         
 [13] "t03_03"          "t03_04"          "t04_01"          "t04_02"         
 [17] "t04_03"          "t04_04"          "t04_05"          "t04_06"         
 [21] "t04_07"          "t05"             "t06_01"          "t06_02"         
 [25] "t06_03"          "t06_04"          "t06_05"          "t06_06"         
 [29] "t06_07"          "t06_08"          "t07_01"          "t07_02"         
 [33] "t08"             "t09_01"          "t09_02"          "t09_03"         
 [37] "t10"             "t11_01"          "t11_02"          "t11_03"         
 [41] "t11_04"          "r01_01"          "r02_01"          "r01_02"         
 [45] "r02_02"          "r01_03"          "r02_03"          "r01_04"         
 [49] "r02_04"          "r01_05"          "r02_05"          "r01_06"         
 [53] "r02_06"          "r01_07"          "r02_07"          "r01_08"         
 [57] "r02_08"          "r01_09"          "r02_09"          "r01_10"         
 [61] "r02_10"          "r01_11"          "r02_11"          "r01_12"         
 [65] "r02_12"          "r01_13"          "r02_13"          "r03_01"         
 [69] "r03_02"          "r03_03"          "r03_04"          "r03_05"         
 [73] "r03_06"          "r03_07"          "r03_08"          "r04_01"         
 [77] "r04_02"          "r04_03"          "r04_04"          "r05_01"         
 [81] "r05_02"          "r06"             "r07"             "r08"            
 [85] "r09"             "r10"             "r11"             "r12_01"         
 [89] "r12_02"          "r12_03"          "r12_04"          "r12_05"         
 [93] "r12_06"          "r12_07"          "c01"             "c02"            
 [97] "c03"             "c04"             "c05_01"          "c05_02"         
[101] "c05_03"          "c05_04"          "c05_05"          "c05_06"         
[105] "c05_07"          "c05_08"          "c06_01"          "c06_02"         
[109] "c06_03"          "c06_04"          "c06_05"          "c06_06"         
[113] "c07_01"          "c07_02"          "c07_03"          "c07_04"         
[117] "c07_05"          "c07_06"          "c07_07"          "c07_08"         
[121] "c08_01"          "c08_02"          "c08_03"          "c08_04"         
[125] "c09_01"          "c09_02"          "c09_03"          "c09_04"         
[129] "c10_01"          "c10_02"          "c10_03"          "c11"            
[133] "c12_01"          "c12_02"          "c12_03"          "c12_04"         
[137] "c12_05"          "c12_06"          "c12_07"          "c12_08"         
[141] "c12_09"          "c12_09_otro"     "c13"             "c14_01"         
[145] "c14_02"          "c15"             "c16"             "c16_otro"       
[149] "c17"             "c17_otro"        "c18_01"          "c18_02"         
[153] "c18_03"          "c18_04"          "c18_05"          "c18_06"         
[157] "c18_07"          "c18_08"          "c18_09"          "c18_10"         
[161] "c18_11"          "c19_01"          "c19_02"          "c19_03"         
[165] "c19_04"          "c20"             "c20_otro"        "c21_01"         
[169] "c21_02"          "c21_03"          "c21_04"          "c21_05"         
[173] "c21_06"          "c21_07"          "c21_08"          "c21_09"         
[177] "c21_10"          "c21_11"          "c22"             "c23"            
[181] "c24"             "c25"             "c26"             "c27"            
[185] "c28"             "c29"             "c30"             "c31"            
[189] "c32_01"          "c32_02"          "c33"             "c34"            
[193] "c35_01"          "c35_02"          "c35_03"          "c35_04"         
[197] "d01_01"          "d01_02"          "d01_03"          "d02_01"         
[201] "d02_02"          "d02_03"          "d03_01"          "d03_02"         
[205] "d04_01"          "d04_02"          "d05_01"          "d05_02"         
[209] "d05_03"          "d05_04"          "d06"             "d07"            
[213] "d08"             "d09"             "d10"             "d11"            
[217] "d12"             "d13"             "d14"             "d15"            
[221] "d16"             "d17"             "d18"             "d19"            
[225] "f01_01"          "f01_02"          "f01_03"          "f01_04"         
[229] "f01_05"          "f01_06"          "f01_07"          "f02_01"         
[233] "f02_02"          "f02_03"          "f02_04"          "f03_01"         
[237] "f03_02"          "f04_01"          "f04_02"          "f05_01"         
[241] "f05_02"          "f05_03"          "f05_04"          "f05_05"         
[245] "f05_06"          "f05_07"          "f05_08"          "f06_01"         
[249] "f06_02"          "s01"             "s02"             "s03"            
[253] "s04"             "s05"             "s06"             "s07"            
[257] "s08"             "s09"             "s10"             "s11_01"         
[261] "s11_02"          "s11_03"          "s11_04"          "s11_05"         
[265] "s11_06"          "s11_07"          "s11_08"          "s11_09"         
[269] "s12"             "s13_01"          "s13_02"          "s13_03"         
[273] "s13_04"          "s13_05"          "s13_06"          "s13_07"         
[277] "s13_08"          "s14"             "m0_sexo"         "m0_edad"        
[281] "m01"             "m02"             "m03"             "m04"            
[285] "m05"             "m06"             "m07"             "m08"            
[289] "m09"             "m10"             "m11"             "m12"            
[293] "m13"             "m14"             "m15"             "m16"            
[297] "m17"             "m18"             "m18_otro"        "m19"            
[301] "m20"             "m21"             "m22"             "m23"            
[305] "m24"             "m25"             "m26"             "m27"            
[309] "m28"             "m29"             "m30"             "m31_01"         
[313] "m31_02"          "m31_03"          "m31_04"          "m32"            
[317] "m33"             "m33_otro"        "m34_01"          "m34_02"         
[321] "m34_03"          "m35"             "m36"             "m36_otro"       
[325] "m37_01"          "m37_02"          "m38"             "m38_otro"       
[329] "m39"             "m40_01"          "m40_02"          "m40_comuna"     
[333] "m40_pais"        "m41"             "m42_01"          "m42_02"         
[337] "m42_03"          "m42_04"          "m42_04_otro"     "m43"            
[341] "m44"             "m45"             "m45_otro"        "cod_m03"        
[345] "cod_m04"         "cod_m22"         "cod_m23"         "nhogar1"        
[349] "nhogar2"         "miembro01_sexo"  "miembro01_edad"  "miembro02_sexo" 
[353] "miembro02_edad"  "miembro03_sexo"  "miembro03_edad"  "miembro04_sexo" 
[357] "miembro04_edad"  "miembro05_sexo"  "miembro05_edad"  "miembro06_sexo" 
[361] "miembro06_edad"  "miembro07_sexo"  "miembro07_edad"  "miembro08_sexo" 
[365] "miembro08_edad"  "miembro09_sexo"  "miembro09_edad"  "miembro10_sexo" 
[369] "miembro10_edad"  "miembro11_sexo"  "miembro11_edad"  "miembro12_sexo" 
[373] "miembro12_edad"  "miembro13_sexo"  "miembro13_edad"  "region"         
[377] "region_cod"      "comuna"          "comuna_cod"      "ponderador01"   
[381] "ponderador02"    "fact_exp01"      "fact_exp02"      "estrato"        
[385] "segmento"        "n_visitas_entr"  "prob_entr"       "prob_n_entr"    
[389] "annio_entr"      "mes_entr"        "dia_entr"        "mod_t_dur"      
[393] "mod_r_dur"       "mod_c_dur"       "mod_d_dur"       "mod_f_dur"      
[397] "mod_s_dur"       "mod_m_dur"       "cierre_dur"      "estim_dur"      
[401] "superv"          "tipo_superv"     "annio_superv"    "mes_superv"     
[405] "dia_superv"      "idencuestador"   "varios_enc"      "sexo_enc"       
[409] "annio_enc"       "mes_enc"         "dia_enc"         "civil_enc"      
[413] "nac_enc"         "comuna_car_enc"  "comuna_enc"      "educ_enc"       
[417] "estudios_enc"    "estado_educ_enc" "ies_enc"         "nombre_ies_enc" 
[421] "trabaja_enc"     "motivo_enc"      "exp_campo_enc"   "exp_n_campo_enc"
[425] "exp_capi_enc"    "exp_n_capi_enc"  "exp_annio_enc"   "capacita_enc"   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(elsoc_2016)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2927  428</code></pre>
</div>
</div>
</section>
<section id="selección-de-variables" class="level2">
<h2 class="anchored" data-anchor-id="selección-de-variables">Selección de Variables</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> elsoc_2016 <span class="sc">%&gt;%</span> <span class="fu">select</span>(m0_sexo,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                                   m0_edad,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                                   m01,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                                   c08_01<span class="sc">:</span>c08_04,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>                                   c12_03,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                                   c13,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>                                   c15,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>                                   c22,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>                                   c33,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>                                   c18_11)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(proc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "m0_sexo" "m0_edad" "m01"     "c08_01"  "c08_02"  "c08_03"  "c08_04" 
 [8] "c12_03"  "c13"     "c15"     "c22"     "c33"     "c18_11" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_label</span>(proc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                             m0_sexo 
                                             "Sexo del entrevistado" 
                                                             m0_edad 
                                             "Edad del entrevistado" 
                                                                 m01 
                                                 "Nivel educacional" 
                                                              c08_01 
                 "Frecuencia: Firma carta o peticion apoyando causa" 
                                                              c08_02 
              "Frecuencia: Asiste a marcha o manifestacion pacifica" 
                                                              c08_03 
                                   "Frecuencia: Participa en huelga" 
                                                              c08_04 
      "Frecuencia: Usa redes sociales para opinar en temas publicos" 
                                                              c12_03 
                          "Membresia: Partido o movimiento politico" 
                                                                 c13 
                                            "Interes en la politica" 
                                                                 c15 
                            "Autoubicacion escala izquierda-derecha" 
                                                                 c22 
"Frecuencia: Participacion del entrevistado en el movimiento social" 
                                                                 c33 
                              "Percepcion subjetiva de clase social" 
                                                              c18_11 
"Grado de acuerdo: Las diferencias de ingreso son demasiado grandes" </code></pre>
</div>
</div>
</section>
<section id="procesamiento-de-variables" class="level2">
<h2 class="anchored" data-anchor-id="procesamiento-de-variables">Procesamiento de Variables</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">set_na</span>(., <span class="at">na =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">999</span>, <span class="sc">-</span><span class="dv">888</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(proc_data)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(proc_data)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(proc_data, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=======================================
Statistic   N    Mean  St. Dev. Min Max
---------------------------------------
m0_sexo   1,806 1.602   0.490    1   2 
m0_edad   1,806 45.027  15.233  18  80 
m01       1,806 5.586   2.190    1  10 
c08_01    1,806 1.720   1.026    1   5 
c08_02    1,806 1.396   0.867    1   5 
c08_03    1,806 1.252   0.712    1   5 
c08_04    1,806 1.870   1.268    1   5 
c12_03    1,806 1.074   0.327    1   3 
c13       1,806 1.838   1.144    1   5 
c15       1,806 7.363   3.959    0  12 
c22       1,806 1.598   1.023    1   5 
c33       1,806 2.346   0.814    1   5 
c18_11    1,806 4.316   0.889    1   5 
---------------------------------------</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(proc_data, <span class="at">file =</span> <span class="st">"Input/data proc/proc_data.RData"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Nivel educacional</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>m01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=1806 valid N=1806 mean=5.59 sd=2.19

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 |  13 |  0.72 |    0.72 |   0.72
    2 | 143 |  7.92 |    7.92 |   8.64
    3 | 168 |  9.30 |    9.30 |  17.94
    4 | 230 | 12.74 |   12.74 |  30.68
    5 | 510 | 28.24 |   28.24 |  58.91
    6 |  70 |  3.88 |    3.88 |  62.79
    7 | 276 | 15.28 |   15.28 |  78.07
    8 | 138 |  7.64 |    7.64 |  85.71
    9 | 221 | 12.24 |   12.24 |  97.95
   10 |  37 |  2.05 |    2.05 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> <span class="fu">rename</span>(proc_data, <span class="st">"educacion"</span> <span class="ot">=</span> m01)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>educacion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>educacion <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>educacion, <span class="at">label =</span> <span class="st">"Educación"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>educacion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Educación (x) &lt;numeric&gt; 
# total N=1806 valid N=1806 mean=5.59 sd=2.19

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 |  13 |  0.72 |    0.72 |   0.72
    2 | 143 |  7.92 |    7.92 |   8.64
    3 | 168 |  9.30 |    9.30 |  17.94
    4 | 230 | 12.74 |   12.74 |  30.68
    5 | 510 | 28.24 |   28.24 |  58.91
    6 |  70 |  3.88 |    3.88 |  62.79
    7 | 276 | 15.28 |   15.28 |  78.07
    8 | 138 |  7.64 |    7.64 |  85.71
    9 | 221 | 12.24 |   12.24 |  97.95
   10 |  37 |  2.05 |    2.05 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>educacion <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data<span class="sc">$</span>educacion, <span class="st">"c(1,2)=0; c(3,4)=1; c(5,6,8)=2; c(7,9,10)=3"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>educacion <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>educacion,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Sin Estudios"</span>, <span class="st">"Básica"</span>, <span class="st">"Media"</span>, <span class="st">"Superior"</span>),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="do">## NSE</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>c33)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=1806 valid N=1806 mean=2.35 sd=0.81

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 | 280 | 15.50 |   15.50 |  15.50
    2 | 723 | 40.03 |   40.03 |  55.54
    3 | 715 | 39.59 |   39.59 |  95.13
    4 |  75 |  4.15 |    4.15 |  99.28
    5 |  13 |  0.72 |    0.72 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"NSE"</span> <span class="ot">=</span> c33)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>NSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=1806 valid N=1806 mean=2.35 sd=0.81

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 | 280 | 15.50 |   15.50 |  15.50
    2 | 723 | 40.03 |   40.03 |  55.54
    3 | 715 | 39.59 |   39.59 |  95.13
    4 |  75 |  4.15 |    4.15 |  99.28
    5 |  13 |  0.72 |    0.72 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>NSE <span class="ot">&lt;-</span> <span class="fu">set_label</span>(proc_data<span class="sc">$</span>NSE, <span class="at">label =</span> <span class="st">"Nivel Socioeconómico"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>NSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Nivel Socioeconómico"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>NSE <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(proc_data<span class="sc">$</span>NSE <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="st">"NSE Bajo"</span>,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">ifelse</span>(proc_data<span class="sc">$</span>NSE <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>), <span class="st">"NSE Medio"</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">ifelse</span>(proc_data<span class="sc">$</span>NSE <span class="sc">==</span> <span class="dv">5</span>, <span class="st">"NSE Alto"</span>, <span class="cn">NA</span>)))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>NSE <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>NSE, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"NSE Bajo"</span>, <span class="st">"NSE Medio"</span>, <span class="st">"NSE Alto"</span>))</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>NSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=1806 valid N=1806 mean=1.45 sd=0.51

Value     |    N | Raw % | Valid % | Cum. %
-------------------------------------------
NSE Bajo  | 1003 | 55.54 |   55.54 |  55.54
NSE Medio |  790 | 43.74 |   43.74 |  99.28
NSE Alto  |   13 |  0.72 |    0.72 | 100.00
&lt;NA&gt;      |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Sexo</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>m0_sexo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=1806 valid N=1806 mean=1.60 sd=0.49

Value |    N | Raw % | Valid % | Cum. %
---------------------------------------
    1 |  719 | 39.81 |   39.81 |  39.81
    2 | 1087 | 60.19 |   60.19 | 100.00
 &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>m0_sexo <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data<span class="sc">$</span>m0_sexo, <span class="st">"1=0;2=1"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>m0_sexo <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>m0_sexo,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Hombre"</span>, <span class="st">"Mujer"</span>),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> <span class="fu">rename</span>(proc_data, <span class="st">"sexo"</span> <span class="ot">=</span> m0_sexo)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>sexo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>sexo <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>sexo, <span class="at">label =</span> <span class="st">"Sexo"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>sexo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sexo (x) &lt;categorical&gt; 
# total N=1806 valid N=1806 mean=1.60 sd=0.49

Value  |    N | Raw % | Valid % | Cum. %
----------------------------------------
Hombre |  719 | 39.81 |   39.81 |  39.81
Mujer  | 1087 | 60.19 |   60.19 | 100.00
&lt;NA&gt;   |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Edad</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>m0_edad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=1806 valid N=1806 mean=45.03 sd=15.23

Value |  N | Raw % | Valid % | Cum. %
-------------------------------------
   18 | 13 |  0.72 |    0.72 |   0.72
   19 | 21 |  1.16 |    1.16 |   1.88
   20 | 16 |  0.89 |    0.89 |   2.77
   21 | 32 |  1.77 |    1.77 |   4.54
   22 | 31 |  1.72 |    1.72 |   6.26
   23 | 29 |  1.61 |    1.61 |   7.86
   24 | 36 |  1.99 |    1.99 |   9.86
   25 | 33 |  1.83 |    1.83 |  11.68
   26 | 30 |  1.66 |    1.66 |  13.34
   27 | 33 |  1.83 |    1.83 |  15.17
   28 | 40 |  2.21 |    2.21 |  17.39
   29 | 32 |  1.77 |    1.77 |  19.16
   30 | 51 |  2.82 |    2.82 |  21.98
   31 | 34 |  1.88 |    1.88 |  23.86
   32 | 34 |  1.88 |    1.88 |  25.75
   33 | 36 |  1.99 |    1.99 |  27.74
   34 | 36 |  1.99 |    1.99 |  29.73
   35 | 43 |  2.38 |    2.38 |  32.12
   36 | 44 |  2.44 |    2.44 |  34.55
   37 | 27 |  1.50 |    1.50 |  36.05
   38 | 32 |  1.77 |    1.77 |  37.82
   39 | 23 |  1.27 |    1.27 |  39.09
   40 | 35 |  1.94 |    1.94 |  41.03
   41 | 41 |  2.27 |    2.27 |  43.30
   42 | 41 |  2.27 |    2.27 |  45.57
   43 | 40 |  2.21 |    2.21 |  47.79
   44 | 27 |  1.50 |    1.50 |  49.28
   45 | 29 |  1.61 |    1.61 |  50.89
   46 | 43 |  2.38 |    2.38 |  53.27
   47 | 36 |  1.99 |    1.99 |  55.26
   48 | 44 |  2.44 |    2.44 |  57.70
   49 | 33 |  1.83 |    1.83 |  59.52
   50 | 48 |  2.66 |    2.66 |  62.18
   51 | 35 |  1.94 |    1.94 |  64.12
   52 | 37 |  2.05 |    2.05 |  66.17
   53 | 33 |  1.83 |    1.83 |  68.00
   54 | 40 |  2.21 |    2.21 |  70.21
   55 | 43 |  2.38 |    2.38 |  72.59
   56 | 48 |  2.66 |    2.66 |  75.25
   57 | 30 |  1.66 |    1.66 |  76.91
   58 | 35 |  1.94 |    1.94 |  78.85
   59 | 23 |  1.27 |    1.27 |  80.12
   60 | 36 |  1.99 |    1.99 |  82.12
   61 | 20 |  1.11 |    1.11 |  83.22
   62 | 15 |  0.83 |    0.83 |  84.05
   63 | 25 |  1.38 |    1.38 |  85.44
   64 | 28 |  1.55 |    1.55 |  86.99
   65 | 40 |  2.21 |    2.21 |  89.20
   66 | 22 |  1.22 |    1.22 |  90.42
   67 | 23 |  1.27 |    1.27 |  91.69
   68 | 18 |  1.00 |    1.00 |  92.69
   69 |  8 |  0.44 |    0.44 |  93.13
   70 | 27 |  1.50 |    1.50 |  94.63
   71 | 14 |  0.78 |    0.78 |  95.40
   72 | 11 |  0.61 |    0.61 |  96.01
   73 | 21 |  1.16 |    1.16 |  97.18
   74 | 24 |  1.33 |    1.33 |  98.50
   75 | 23 |  1.27 |    1.27 |  99.78
   77 |  1 |  0.06 |    0.06 |  99.83
   78 |  2 |  0.11 |    0.11 |  99.94
   80 |  1 |  0.06 |    0.06 | 100.00
 &lt;NA&gt; |  0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> <span class="fu">rename</span>(proc_data, <span class="st">"edad"</span> <span class="ot">=</span> m0_edad)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>edad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>edad <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>edad, <span class="at">label =</span> <span class="st">"Edad"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>edad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Edad (x) &lt;numeric&gt; 
# total N=1806 valid N=1806 mean=45.03 sd=15.23

Value |  N | Raw % | Valid % | Cum. %
-------------------------------------
   18 | 13 |  0.72 |    0.72 |   0.72
   19 | 21 |  1.16 |    1.16 |   1.88
   20 | 16 |  0.89 |    0.89 |   2.77
   21 | 32 |  1.77 |    1.77 |   4.54
   22 | 31 |  1.72 |    1.72 |   6.26
   23 | 29 |  1.61 |    1.61 |   7.86
   24 | 36 |  1.99 |    1.99 |   9.86
   25 | 33 |  1.83 |    1.83 |  11.68
   26 | 30 |  1.66 |    1.66 |  13.34
   27 | 33 |  1.83 |    1.83 |  15.17
   28 | 40 |  2.21 |    2.21 |  17.39
   29 | 32 |  1.77 |    1.77 |  19.16
   30 | 51 |  2.82 |    2.82 |  21.98
   31 | 34 |  1.88 |    1.88 |  23.86
   32 | 34 |  1.88 |    1.88 |  25.75
   33 | 36 |  1.99 |    1.99 |  27.74
   34 | 36 |  1.99 |    1.99 |  29.73
   35 | 43 |  2.38 |    2.38 |  32.12
   36 | 44 |  2.44 |    2.44 |  34.55
   37 | 27 |  1.50 |    1.50 |  36.05
   38 | 32 |  1.77 |    1.77 |  37.82
   39 | 23 |  1.27 |    1.27 |  39.09
   40 | 35 |  1.94 |    1.94 |  41.03
   41 | 41 |  2.27 |    2.27 |  43.30
   42 | 41 |  2.27 |    2.27 |  45.57
   43 | 40 |  2.21 |    2.21 |  47.79
   44 | 27 |  1.50 |    1.50 |  49.28
   45 | 29 |  1.61 |    1.61 |  50.89
   46 | 43 |  2.38 |    2.38 |  53.27
   47 | 36 |  1.99 |    1.99 |  55.26
   48 | 44 |  2.44 |    2.44 |  57.70
   49 | 33 |  1.83 |    1.83 |  59.52
   50 | 48 |  2.66 |    2.66 |  62.18
   51 | 35 |  1.94 |    1.94 |  64.12
   52 | 37 |  2.05 |    2.05 |  66.17
   53 | 33 |  1.83 |    1.83 |  68.00
   54 | 40 |  2.21 |    2.21 |  70.21
   55 | 43 |  2.38 |    2.38 |  72.59
   56 | 48 |  2.66 |    2.66 |  75.25
   57 | 30 |  1.66 |    1.66 |  76.91
   58 | 35 |  1.94 |    1.94 |  78.85
   59 | 23 |  1.27 |    1.27 |  80.12
   60 | 36 |  1.99 |    1.99 |  82.12
   61 | 20 |  1.11 |    1.11 |  83.22
   62 | 15 |  0.83 |    0.83 |  84.05
   63 | 25 |  1.38 |    1.38 |  85.44
   64 | 28 |  1.55 |    1.55 |  86.99
   65 | 40 |  2.21 |    2.21 |  89.20
   66 | 22 |  1.22 |    1.22 |  90.42
   67 | 23 |  1.27 |    1.27 |  91.69
   68 | 18 |  1.00 |    1.00 |  92.69
   69 |  8 |  0.44 |    0.44 |  93.13
   70 | 27 |  1.50 |    1.50 |  94.63
   71 | 14 |  0.78 |    0.78 |  95.40
   72 | 11 |  0.61 |    0.61 |  96.01
   73 | 21 |  1.16 |    1.16 |  97.18
   74 | 24 |  1.33 |    1.33 |  98.50
   75 | 23 |  1.27 |    1.27 |  99.78
   77 |  1 |  0.06 |    0.06 |  99.83
   78 |  2 |  0.11 |    0.11 |  99.94
   80 |  1 |  0.06 |    0.06 | 100.00
 &lt;NA&gt; |  0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Participación Política</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"apoyo_causa"</span> <span class="ot">=</span> c08_01,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"part_marcha"</span> <span class="ot">=</span> c08_02,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"part_huelga"</span> <span class="ot">=</span> c08_03,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"rrss_pol"</span> <span class="ot">=</span> c08_04)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>apoyo_causa <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>apoyo_causa, <span class="at">label =</span> <span class="st">"Participación: Apoya Causa"</span>)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>apoyo_causa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Participación: Apoya Causa"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>part_marcha <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>part_marcha, <span class="at">label =</span> <span class="st">"Participación: Marcha"</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>part_marcha)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Participación: Marcha"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>part_huelga <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>part_huelga, <span class="at">label =</span> <span class="st">"Participación: Huelga"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>part_huelga)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Participación: Huelga"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>rrss_pol <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>rrss_pol, <span class="at">label =</span> <span class="st">"Participación: RRSS"</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>rrss_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Participación: RRSS"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>apoyo_causa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Participación: Apoya Causa (x) &lt;numeric&gt; 
# total N=1806 valid N=1806 mean=1.72 sd=1.03

Value |    N | Raw % | Valid % | Cum. %
---------------------------------------
    1 | 1120 | 62.02 |   62.02 |  62.02
    2 |  202 | 11.18 |   11.18 |  73.20
    3 |  376 | 20.82 |   20.82 |  94.02
    4 |   85 |  4.71 |    4.71 |  98.73
    5 |   23 |  1.27 |    1.27 | 100.00
 &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>part_marcha)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Participación: Marcha (x) &lt;numeric&gt; 
# total N=1806 valid N=1806 mean=1.40 sd=0.87

Value |    N | Raw % | Valid % | Cum. %
---------------------------------------
    1 | 1443 | 79.90 |   79.90 |  79.90
    2 |  104 |  5.76 |    5.76 |  85.66
    3 |  183 | 10.13 |   10.13 |  95.79
    4 |   59 |  3.27 |    3.27 |  99.06
    5 |   17 |  0.94 |    0.94 | 100.00
 &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>part_huelga)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Participación: Huelga (x) &lt;numeric&gt; 
# total N=1806 valid N=1806 mean=1.25 sd=0.71

Value |    N | Raw % | Valid % | Cum. %
---------------------------------------
    1 | 1571 | 86.99 |   86.99 |  86.99
    2 |   70 |  3.88 |    3.88 |  90.86
    3 |  119 |  6.59 |    6.59 |  97.45
    4 |   36 |  1.99 |    1.99 |  99.45
    5 |   10 |  0.55 |    0.55 | 100.00
 &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>rrss_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Participación: RRSS (x) &lt;numeric&gt; 
# total N=1806 valid N=1806 mean=1.87 sd=1.27

Value |    N | Raw % | Valid % | Cum. %
---------------------------------------
    1 | 1142 | 63.23 |   63.23 |  63.23
    2 |  114 |  6.31 |    6.31 |  69.55
    3 |  275 | 15.23 |   15.23 |  84.77
    4 |  192 | 10.63 |   10.63 |  95.40
    5 |   83 |  4.60 |    4.60 | 100.00
 &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>apoyo_causa <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>apoyo_causa,</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Poco"</span>, <span class="st">"Poco"</span>, <span class="st">"Algo"</span>, <span class="st">"Mucha"</span>, <span class="st">"Mucha"</span>))</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>part_marcha <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>part_marcha,</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Poco"</span>, <span class="st">"Poco"</span>, <span class="st">"Algo"</span>, <span class="st">"Mucha"</span>, <span class="st">"Mucha"</span>))</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>part_huelga <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>part_huelga,</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Poco"</span>, <span class="st">"Poco"</span>, <span class="st">"Algo"</span>, <span class="st">"Mucha"</span>, <span class="st">"Mucha"</span>))</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>rrss_pol <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>rrss_pol,</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>                             <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Poco"</span>, <span class="st">"Poco"</span>, <span class="st">"Algo"</span>, <span class="st">"Mucha"</span>, <span class="st">"Mucha"</span>))</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a><span class="do">## Membresías</span></span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"pert_pp"</span> <span class="ot">=</span> c12_03)</span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-18"><a href="#cb55-18" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>pert_pp <span class="ot">&lt;-</span> <span class="fu">set_label</span>(proc_data<span class="sc">$</span>pert_pp, <span class="at">label =</span> <span class="st">"Pertenece: Partido Político"</span>)</span>
<span id="cb55-19"><a href="#cb55-19" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>pert_pp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Pertenece: Partido Político"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>pert_pp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pertenece: Partido Político (x) &lt;numeric&gt; 
# total N=1806 valid N=1806 mean=1.07 sd=0.33

Value |    N | Raw % | Valid % | Cum. %
---------------------------------------
    1 | 1708 | 94.57 |   94.57 |  94.57
    2 |   63 |  3.49 |    3.49 |  98.06
    3 |   35 |  1.94 |    1.94 | 100.00
 &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>pert_pp <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>pert_pp,</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Si"</span>, <span class="st">"Si"</span>))</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Interés en la política</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"interes_pol"</span> <span class="ot">=</span> c13)</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>interes_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=1806 valid N=1806 mean=1.84 sd=1.14

Value |    N | Raw % | Valid % | Cum. %
---------------------------------------
    1 | 1019 | 56.42 |   56.42 |  56.42
    2 |  329 | 18.22 |   18.22 |  74.64
    3 |  254 | 14.06 |   14.06 |  88.70
    4 |  140 |  7.75 |    7.75 |  96.46
    5 |   64 |  3.54 |    3.54 | 100.00
 &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>interes_pol <span class="ot">&lt;-</span> <span class="fu">set_label</span>(proc_data<span class="sc">$</span>interes_pol, <span class="at">label =</span> <span class="st">"Interés Político"</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>interes_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Interés Político"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>interes_pol <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>interes_pol,</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Sin interés"</span>, <span class="st">"Poco interés"</span>, <span class="st">"Poco interés"</span>, <span class="st">"Alto interés"</span>, <span class="st">"Alto interés"</span>))</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Participación en Movimientos Sociales</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"part_movsoc"</span> <span class="ot">=</span> c22)</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>part_movsoc <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>part_movsoc, <span class="at">label =</span> <span class="st">"Participación: Movimientos Sociales"</span>)</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>part_movsoc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Participación: Movimientos Sociales"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>part_movsoc <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>part_movsoc,</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Poco"</span>, <span class="st">"Poco"</span>, <span class="st">"Algo"</span>, <span class="st">"Mucha"</span>, <span class="st">"Mucha"</span>))</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>part_movsoc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=1806 valid N=1806 mean=1.28 sd=0.59

Value |    N | Raw % | Valid % | Cum. %
---------------------------------------
Poco  | 1425 | 78.90 |   78.90 |  78.90
Algo  |  250 | 13.84 |   13.84 |  92.75
Mucha |  131 |  7.25 |    7.25 | 100.00
&lt;NA&gt;  |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Autoubicación Política</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"autoubicpol"</span> <span class="ot">=</span> c15)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>autoubicpol <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>autoubicpol, <span class="at">label =</span> <span class="st">"Autoubicación Política"</span>)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>autoubicpol <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data<span class="sc">$</span>autoubicpol, <span class="st">"c(0,1,2,3,4)=1; c(5)=2; c(6,8,9,10,11)=3"</span>)</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>autoubicpol <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>autoubicpol,</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>                              <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Izquierda"</span>, <span class="st">"Centro"</span>, <span class="st">"Derecha"</span>),</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>                              <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(autoubicpol))</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>autoubicpol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=1181 valid N=1181 mean=1.93 sd=0.80

Value     |   N | Raw % | Valid % | Cum. %
------------------------------------------
Izquierda | 417 | 35.31 |   35.31 |  35.31
Centro    | 429 | 36.33 |   36.33 |  71.63
Derecha   | 335 | 28.37 |   28.37 | 100.00
&lt;NA&gt;      |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Desigualdad de ingreso</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"percep_desigualdad"</span> <span class="ot">=</span> c18_11)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>percep_desigualdad <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>percep_desigualdad, <span class="at">label =</span> <span class="st">"Percepción Desigualdad"</span>)</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>percep_desigualdad <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_data<span class="sc">$</span>percep_desigualdad, <span class="st">"1:2=1; 3=2; 4:5=3"</span>)</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>percep_desigualdad <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_data<span class="sc">$</span>percep_desigualdad,</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No percibe desigualdad"</span>, <span class="st">"Indeciso"</span>, <span class="st">"Percibe desigualdad"</span>))</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>percep_desigualdad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=1181 valid N=1181 mean=2.82 sd=0.55

Value                  |    N | Raw % | Valid % | Cum. %
--------------------------------------------------------
No percibe desigualdad |   91 |  7.71 |    7.71 |   7.71
Indeciso               |   36 |  3.05 |    3.05 |  10.75
Percibe desigualdad    | 1054 | 89.25 |   89.25 | 100.00
&lt;NA&gt;                   |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
</section>
<section id="descriptivos" class="level2">
<h2 class="anchored" data-anchor-id="descriptivos">Descriptivos</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(proc_data, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=======================================
Statistic   N    Mean  St. Dev. Min Max
---------------------------------------
edad      1,181 45.107  15.524  18  78 
---------------------------------------</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">descr</span>(proc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
## Basic descriptive statistics

                var        type              label    n NA.prc  mean    sd   se
               sexo categorical               Sexo 1181      0  1.57  0.49 0.01
               edad     numeric               Edad 1181      0 45.11 15.52 0.45
          educacion categorical          educacion 1181      0  2.95  0.92 0.03
        apoyo_causa categorical        apoyo_causa 1181      0  1.36  0.60 0.02
        part_marcha categorical        part_marcha 1181      0  1.22  0.53 0.02
        part_huelga categorical        part_huelga 1181      0  1.13  0.41 0.01
           rrss_pol categorical           rrss_pol 1181      0  1.49  0.77 0.02
            pert_pp categorical            pert_pp 1181      0  1.07  0.26 0.01
        interes_pol categorical        interes_pol 1181      0  1.67  0.73 0.02
        autoubicpol categorical        autoubicpol 1181      0  1.93  0.80 0.02
        part_movsoc categorical        part_movsoc 1181      0  1.32  0.62 0.02
                NSE categorical                NSE 1181      0  1.49  0.52 0.02
 percep_desigualdad categorical percep_desigualdad 1181      0  2.82  0.55 0.02
 md trimmed      range iqr  skew
  2    1.59    1 (1-2)   1 -0.30
 45   44.76 60 (18-78)  25  0.13
  3    3.04    3 (1-4)   2 -0.53
  1    1.24    2 (1-3)   1  1.46
  1    1.09    2 (1-3)   0  2.33
  1    1.01    2 (1-3)   0  3.21
  1    1.36    2 (1-3)   1  1.16
  1    1.00    1 (1-2)   0  3.34
  2    1.58    2 (1-3)   1  0.61
  2    1.91    2 (1-3)   2  0.12
  1    1.18    2 (1-3)   0  1.74
  1    1.47    2 (1-3)   1  0.29
  3    2.99    2 (1-3)   0 -2.81</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">descr</span>(proc_data,</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">show =</span> <span class="fu">c</span>(<span class="st">"label"</span>,<span class="st">"range"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"NA.prc"</span>, <span class="st">"n"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(.,<span class="st">"markdown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">var</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">NA.prc</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: left;">range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">sexo</td>
<td style="text-align: left;">Sexo</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.574936</td>
<td style="text-align: right;">0.4945621</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">edad</td>
<td style="text-align: left;">Edad</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">45.106689</td>
<td style="text-align: right;">15.5237532</td>
<td style="text-align: left;">60 (18-78)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">educacion</td>
<td style="text-align: left;">educacion</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.952583</td>
<td style="text-align: right;">0.9239491</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">apoyo_causa</td>
<td style="text-align: left;">apoyo_causa</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.358171</td>
<td style="text-align: right;">0.6004897</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: left;">part_marcha</td>
<td style="text-align: left;">part_marcha</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.221846</td>
<td style="text-align: right;">0.5255154</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">part_huelga</td>
<td style="text-align: left;">part_huelga</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.134632</td>
<td style="text-align: right;">0.4133304</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12</td>
<td style="text-align: left;">rrss_pol</td>
<td style="text-align: left;">rrss_pol</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.489416</td>
<td style="text-align: right;">0.7664123</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">11</td>
<td style="text-align: left;">pert_pp</td>
<td style="text-align: left;">pert_pp</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.071126</td>
<td style="text-align: right;">0.2571444</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">interes_pol</td>
<td style="text-align: left;">interes_pol</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.665538</td>
<td style="text-align: right;">0.7323560</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">autoubicpol</td>
<td style="text-align: left;">autoubicpol</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.930567</td>
<td style="text-align: right;">0.7952755</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">part_movsoc</td>
<td style="text-align: left;">part_movsoc</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.324301</td>
<td style="text-align: right;">0.6221835</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">NSE</td>
<td style="text-align: left;">NSE</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.486876</td>
<td style="text-align: right;">0.5216065</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: left;">percep_desigualdad</td>
<td style="text-align: left;">percep_desigualdad</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.815411</td>
<td style="text-align: right;">0.5521603</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>summarytools<span class="sc">::</span><span class="fu">dfSummary</span>(proc_data, <span class="at">plain.ascii =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>### Data Frame Summary  
#### proc_data  
**Label:** Estudio Longitudinal Social de Chile. Ola 2016. Version 4.00 (10/06/2020)  
**Dimensions:** 1181 x 13  
**Duplicates:** 23  

----------------------------------------------------------------------------------------------------------------------------------
No   Variable              Label   Stats / Values                Freqs (% of Valid)   Graph                   Valid      Missing  
---- --------------------- ------- ----------------------------- -------------------- ----------------------- ---------- ---------
1    sexo\                 Sexo    1\. Hombre\                   502 (42.5%)\         IIIIIIII \              1181\      0\       
     [factor]                      2\. Mujer                     679 (57.5%)          IIIIIIIIIII             (100.0%)   (0.0%)   

2    edad\                 Edad    Mean (sd) : 45.1 (15.5)\      59 distinct values   \ \ : : \ \ . . :\      1181\      0\       
     [numeric]                     min &lt; med &lt; max:\                                  : : : : : : : .\        (100.0%)   (0.0%)   
                                   18 &lt; 45 &lt; 78\                                      : : : : : : : :\                            
                                   IQR (CV) : 25 (0.3)                                : : : : : : : : : .\                        
                                                                                      : : : : : : : : : :                         

3    educacion\                    1\. Sin Estudios\             96 ( 8.1%)\          I \                     1181\      0\       
     [factor]                      2\. Básica\                   245 (20.7%)\         IIII \                  (100.0%)   (0.0%)   
                                   3\. Media\                    459 (38.9%)\         IIIIIII \                                   
                                   4\. Superior                  381 (32.3%)          IIIIII                                      

4    apoyo_causa\                  1\. Poco\                     835 (70.7%)\         IIIIIIIIIIIIII \        1181\      0\       
     [factor]                      2\. Algo\                     269 (22.8%)\         IIII \                  (100.0%)   (0.0%)   
                                   3\. Mucha                     77 ( 6.5%)           I                                           

5    part_marcha\                  1\. Poco\                     980 (83.0%)\         IIIIIIIIIIIIIIII \      1181\      0\       
     [factor]                      2\. Algo\                     140 (11.9%)\         II \                    (100.0%)   (0.0%)   
                                   3\. Mucha                     61 ( 5.2%)           I                                           

6    part_huelga\                  1\. Poco\                     1054 (89.2%)\        IIIIIIIIIIIIIIIII \     1181\      0\       
     [factor]                      2\. Algo\                     95 ( 8.0%)\          I \                     (100.0%)   (0.0%)   
                                   3\. Mucha                     32 ( 2.7%)                                                       

7    rrss_pol\                     1\. Poco\                     802 (67.9%)\         IIIIIIIIIIIII \         1181\      0\       
     [factor]                      2\. Algo\                     180 (15.2%)\         III \                   (100.0%)   (0.0%)   
                                   3\. Mucha                     199 (16.9%)          III                                         

8    pert_pp\                      1\. No\                       1097 (92.9%)\        IIIIIIIIIIIIIIIIII \    1181\      0\       
     [factor]                      2\. Si                        84 ( 7.1%)           I                       (100.0%)   (0.0%)   

9    interes_pol\                  1\. Sin interés\              580 (49.1%)\         IIIIIIIII \             1181\      0\       
     [factor]                      2\. Poco interés\             416 (35.2%)\         IIIIIII \               (100.0%)   (0.0%)   
                                   3\. Alto interés              185 (15.7%)          III                                         

10   autoubicpol\                  1\. Izquierda\                417 (35.3%)\         IIIIIII \               1181\      0\       
     [factor]                      2\. Centro\                   429 (36.3%)\         IIIIIII \               (100.0%)   (0.0%)   
                                   3\. Derecha                   335 (28.4%)          IIIII                                       

11   part_movsoc\                  1\. Poco\                     897 (76.0%)\         IIIIIIIIIIIIIII \       1181\      0\       
     [factor]                      2\. Algo\                     185 (15.7%)\         III \                   (100.0%)   (0.0%)   
                                   3\. Mucha                     99 ( 8.4%)           I                                           

12   NSE\                          1\. NSE Bajo\                 619 (52.4%)\         IIIIIIIIII \            1181\      0\       
     [factor]                      2\. NSE Medio\                549 (46.5%)\         IIIIIIIII \             (100.0%)   (0.0%)   
                                   3\. NSE Alto                  13 ( 1.1%)                                                       

13   percep_desigualdad\           1\. No percibe desigualdad\   91 ( 7.7%)\          I \                     1181\      0\       
     [factor]                      2\. Indeciso\                 36 ( 3.0%)\          \                       (100.0%)   (0.0%)   
                                   3\. Percibe desigualdad       1054 (89.2%)         IIIIIIIIIIIIIIIII                           
----------------------------------------------------------------------------------------------------------------------------------</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(<span class="fu">dfSummary</span>(proc_data, <span class="at">headings =</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Switching method to 'browser'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Output file written: C:\Users\sivim\AppData\Local\Temp\RtmpWKzCEA\file6d0c7b26678e.html</code></pre>
</div>
</div>
<p>Como se observa en la tabla, la muestra final está compuesta en un 42,5% por hombres y un 57,5% de mujeres. La edad varía entre los 18 y 78 años,. El promedio de edad es de 45 años, con una desviación estándar de 15,5 años., lo que indica una dispersión considerable. Se puede observar que un 32,3% de los encuestados han cursado estudios superiores, un 59,6% han cursado estudios de básica y/o media, y sólo un 8,1% no cuenta con estudios. En el resto de variables que abarcan participación política, la mayoría de los encuestados reportan poco apoyo a causas (70,7%), poca participación en marchas (83%), poca participación en huelgas (89,2%), y poco uso de redes sociales para fines políticos (67,9%). Respecto a la pertenencia, la mayoría de los encuestados no son miembros de partidos políticos (92.9%). Alrededor del 35,2% de los encuestados reportan poco interés político, mientras que el 49,1% se reporta sin interés y sólo el 15,7% reporta alto interés. La mayoría reportan una participación baja en movimientos sociales (76%). En cuanto a la ubicación política, la mayoría se autopercibe como centro (36,3%), seguido de izquierda con un 35,3% y derecha con un 28,4%. La mayoría de los encuestados tienen un nivel socioeconómico bajo (52,4%), seguido por un 46,5% con nivel socioeconómico medio y solo un pequeño porcentaje (1,1%) con nivel socioeconómico alto. Finalmente, la percepción de desigualdad de los encuestados es alta, pues el 89,2% de la muestra cree que en Chile existe una desigualdad de ingresos.</p>
</section>
<section id="gráficos" class="level2">
<h2 class="anchored" data-anchor-id="gráficos">Gráficos</h2>
<div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: “Gráfico 1”</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>graph1 <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(apoyo_causa, part_marcha, part_huelga, rrss_pol, part_movsoc) <span class="sc">%&gt;%</span></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Participación en Causa"</span> <span class="ot">=</span> apoyo_causa,</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Participación en Marcha"</span> <span class="ot">=</span> part_marcha,</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Participación en Huelga"</span> <span class="ot">=</span> part_huelga,</span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Participación en RRSS"</span> <span class="ot">=</span> rrss_pol,</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Participación en Movimientos Sociales"</span> <span class="ot">=</span> part_movsoc</span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a>  sjPlot<span class="sc">::</span><span class="fu">plot_stackfrq</span>() <span class="sc">+</span></span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="sc">+</span></span>
<span id="cb81-14"><a href="#cb81-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb81-15"><a href="#cb81-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Participación en diferentes actividades sociales"</span>,</span>
<span id="cb81-16"><a href="#cb81-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Actividades"</span>,</span>
<span id="cb81-17"><a href="#cb81-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Frecuencia"</span></span>
<span id="cb81-18"><a href="#cb81-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb81-19"><a href="#cb81-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-20"><a href="#cb81-20" aria-hidden="true" tabindex="-1"></a>graph1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-sjPlot" class="cell tbl-parent quarto-layout-panel anchored">
<div class="panel-caption table-caption">
<p><strong>?(caption)</strong></p>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p><img src="desigualdad-pp3_files/figure-html/tbl-sjPlot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p>El gráfico ilustra la frecuencia de participación en diferentes actividades sociales en una muestra de 1181 individuos. Los resultados muestran que la mayoría de los individuos reportan una baja participación en todas las actividades. Específicamente, un 75.9% reporta poca participación en movimientos sociales, 67.9% en RRSS, 89.2% en huelgas, 83.0% en marchas y 70.7% en causas. En el caso de la participación por redes sociales, nos encontramos con los valores más altos respecto a que participan algo o mucho en ellas. La participación moderada (“Algo”) y alta (“Mucha”) en RRSS (32.1% combinados) y en causas (29.3% combinados), sugiere que estas áreas pueden ser puntos clave para aumentar el compromiso social.</p>
<div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: “Gráfico 2”</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>graph2 <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> interes_pol, <span class="at">fill =</span> percep_desigualdad)) <span class="sc">+</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Interés Político"</span>) <span class="sc">+</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Cantidad"</span>) <span class="sc">+</span></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"Percepción Desigualdad"</span>) <span class="sc">+</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'No percibe desigualdad'</span>, <span class="st">'Indeciso'</span>, <span class="st">'Percibe desigualdad'</span>)) <span class="sc">+</span></span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Relación entre Interés Político y Desigualdad"</span>)</span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a>graph2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-ggplot" class="cell tbl-parent quarto-layout-panel anchored">
<div class="panel-caption table-caption">
<p><strong>?(caption)</strong></p>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p><img src="desigualdad-pp3_files/figure-html/tbl-ggplot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p>Este gráfico examina la relación entre el interés político y la percepción de desigualdad. La distribución muestra que la mayoría de los individuos con “Sin interés” político perciben desigualdad (representado en azul), seguido de un grupo menor que no percibe desigualdad (rojo) y un grupo aún menor de indecisos (verde). Entre aquellos con “Poco interés” político, se mantiene una tendencia similar, aunque con una ligera reducción en los números. Los individuos con “Alto interés” político son significativamente menos, pero la mayoría en esta categoría también perciben desigualdad. Este patrón indica que la percepción de desigualdad podría estar correlacionada con el nivel de interés político, sugiriendo que quienes perciben desigualdad tienden a tener mayor interés en la política.</p>
<p>El estudio sobre las tendencias de desigualdad y participación política en Chile destaca la compleja interacción entre factores sociales, económicos y educativos en la configuración de actitudes políticas y comportamientos cívicos. La desigualdad social y económica en Chile no solo afecta la calidad de vida de los ciudadanos, sino que también influye en su participación política y en la percepción de las instituciones democráticas.</p>
<p>La educación cívica emerge como una herramienta esencial para abordar estas desigualdades y fomentar la participación ciudadana informada. Sin embargo, el estudio sugiere que el nivel socioeconómico también desempeña un papel significativo en el grado de interés político , lo que subraya la importancia de considerar el contexto socioeconómico al analizar la participación política.</p>
<p>La hipótesis planteada en el estudio, que sugiere que una mayor percepción de la desigualdad social se relaciona con una mayor participación política, abre nuevas vías de investigación sobre cómo los chilenos responden a las disparidades socioeconómicas y buscan influir en el cambio social y económico a través de la acción política.</p>
</section>
<section id="asociación-de-variables" class="level2">
<h2 class="anchored" data-anchor-id="asociación-de-variables">Asociación de Variables</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(proc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1181   13</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">descr</span>(proc_data,</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">show =</span> <span class="fu">c</span>(<span class="st">"label"</span>, <span class="st">"range"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"NA.prc"</span>, <span class="st">"n"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(.,<span class="st">"markdown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">var</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">NA.prc</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: left;">range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">sexo</td>
<td style="text-align: left;">Sexo</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.574936</td>
<td style="text-align: right;">0.4945621</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">edad</td>
<td style="text-align: left;">Edad</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">45.106689</td>
<td style="text-align: right;">15.5237532</td>
<td style="text-align: left;">60 (18-78)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">educacion</td>
<td style="text-align: left;">educacion</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.952583</td>
<td style="text-align: right;">0.9239491</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">apoyo_causa</td>
<td style="text-align: left;">apoyo_causa</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.358171</td>
<td style="text-align: right;">0.6004897</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: left;">part_marcha</td>
<td style="text-align: left;">part_marcha</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.221846</td>
<td style="text-align: right;">0.5255154</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">part_huelga</td>
<td style="text-align: left;">part_huelga</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.134632</td>
<td style="text-align: right;">0.4133304</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12</td>
<td style="text-align: left;">rrss_pol</td>
<td style="text-align: left;">rrss_pol</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.489416</td>
<td style="text-align: right;">0.7664123</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">11</td>
<td style="text-align: left;">pert_pp</td>
<td style="text-align: left;">pert_pp</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.071126</td>
<td style="text-align: right;">0.2571444</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">interes_pol</td>
<td style="text-align: left;">interes_pol</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.665538</td>
<td style="text-align: right;">0.7323560</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">autoubicpol</td>
<td style="text-align: left;">autoubicpol</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.930567</td>
<td style="text-align: right;">0.7952755</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">part_movsoc</td>
<td style="text-align: left;">part_movsoc</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.324301</td>
<td style="text-align: right;">0.6221835</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">NSE</td>
<td style="text-align: left;">NSE</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.486876</td>
<td style="text-align: right;">0.5216065</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: left;">percep_desigualdad</td>
<td style="text-align: left;">percep_desigualdad</td>
<td style="text-align: right;">1181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.815411</td>
<td style="text-align: right;">0.5521603</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="correlación" class="level2">
<h2 class="anchored" data-anchor-id="correlación">Correlación</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> <span class="fu">mutate_all</span>(proc_data, as.numeric)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cor</span>(proc_data,</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>M</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          sexo         edad   educacion apoyo_causa part_marcha
sexo                1.00000000  0.100840873 -0.07938328  0.01940973 -0.03793298
edad                0.10084087  1.000000000 -0.24118424 -0.10728658 -0.16952875
educacion          -0.07938328 -0.241184245  1.00000000  0.14366739  0.18749224
apoyo_causa         0.01940973 -0.107286582  0.14366739  1.00000000  0.30389030
part_marcha        -0.03793298 -0.169528752  0.18749224  0.30389030  1.00000000
part_huelga        -0.05976014 -0.091259713  0.12546530  0.21528103  0.43590458
rrss_pol           -0.02529436 -0.308826551  0.24342993  0.30010736  0.33618138
pert_pp            -0.06193754  0.005740114  0.07841176  0.10380312  0.17788425
interes_pol        -0.05358116 -0.124399423  0.26710237  0.23216482  0.26562107
autoubicpol         0.02832261  0.021674295 -0.01601767 -0.07210102 -0.19224845
part_movsoc        -0.07215912 -0.173100956  0.18745843  0.24229727  0.36035622
NSE                -0.06763610 -0.040748753  0.29764198  0.07048630  0.03227247
percep_desigualdad  0.02587009  0.025236895  0.08748032  0.02065513  0.04194639
                    part_huelga    rrss_pol      pert_pp interes_pol
sexo               -0.059760137 -0.02529436 -0.061937541 -0.05358116
edad               -0.091259713 -0.30882655  0.005740114 -0.12439942
educacion           0.125465298  0.24342993  0.078411760  0.26710237
apoyo_causa         0.215281028  0.30010736  0.103803118  0.23216482
part_marcha         0.435904582  0.33618138  0.177884250  0.26562107
part_huelga         1.000000000  0.22253187  0.101189965  0.18527720
rrss_pol            0.222531866  1.00000000  0.128526003  0.28282359
pert_pp             0.101189965  0.12852600  1.000000000  0.24343027
interes_pol         0.185277204  0.28282359  0.243430265  1.00000000
autoubicpol        -0.108178420 -0.05126092 -0.013126870 -0.12720914
part_movsoc         0.245293254  0.30844025  0.157629006  0.28474088
NSE                 0.010168080  0.08815746 -0.011989192  0.06059925
percep_desigualdad  0.001298541  0.06947485  0.014954466  0.10287243
                   autoubicpol part_movsoc         NSE percep_desigualdad
sexo                0.02832261 -0.07215912 -0.06763610        0.025870086
edad                0.02167429 -0.17310096 -0.04074875        0.025236895
educacion          -0.01601767  0.18745843  0.29764198        0.087480325
apoyo_causa        -0.07210102  0.24229727  0.07048630        0.020655126
part_marcha        -0.19224845  0.36035622  0.03227247        0.041946388
part_huelga        -0.10817842  0.24529325  0.01016808        0.001298541
rrss_pol           -0.05126092  0.30844025  0.08815746        0.069474851
pert_pp            -0.01312687  0.15762901 -0.01198919        0.014954466
interes_pol        -0.12720914  0.28474088  0.06059925        0.102872434
autoubicpol         1.00000000 -0.08633267  0.04683212       -0.063949856
part_movsoc        -0.08633267  1.00000000  0.06665775        0.031322750
NSE                 0.04683212  0.06665775  1.00000000        0.071027525
percep_desigualdad -0.06394986  0.03132275  0.07102753        1.000000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_corr</span>(proc_data, </span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">triangle =</span> <span class="st">"lower"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">&nbsp;</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">sexo</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">edad</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">educacion</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">apoyo_causa</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">part_marcha</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">part_huelga</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">rrss_pol</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">pert_pp</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">interes_pol</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">autoubicpol</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">part_movsoc</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">NSE</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">percep_desigualdad</td>
</tr>
<tr class="even">
<td style="font-style: italic">sexo</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">edad</td>
<td style="text-align: center; padding: 0.2cm;">0.101<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">educacion</td>
<td style="text-align: center; padding: 0.2cm;">-0.079<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.241<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">apoyo_causa</td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.019<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">-0.107<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.144<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">part_marcha</td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.038<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">-0.170<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.187<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.304<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">part_huelga</td>
<td style="text-align: center; padding: 0.2cm;">-0.060<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.091<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm;">0.125<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.215<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.436<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">rrss_pol</td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.025<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">-0.309<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.243<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.300<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.336<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.223<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">pert_pp</td>
<td style="text-align: center; padding: 0.2cm;">-0.062<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.006<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.078<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm;">0.104<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.178<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.101<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.129<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">interes_pol</td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.054<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">-0.124<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.267<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.232<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.266<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.185<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.283<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.243<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">autoubicpol</td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.028<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.022<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.016<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">-0.072<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.192<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.108<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.051<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.013<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">-0.127<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">part_movsoc</td>
<td style="text-align: center; padding: 0.2cm;">-0.072<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.173<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.187<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.242<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.360<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.245<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.308<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.158<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.285<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.086<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">NSE</td>
<td style="text-align: center; padding: 0.2cm;">-0.068<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.041<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.298<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.070<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.032<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.010<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.088<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.012<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.061<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.047<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.067<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">percep_desigualdad</td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.026<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.025<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.087<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.021<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.042<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.001<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.069<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.015<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.103<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.064<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.031<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.071<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td colspan="14" style="text-align: right; border-bottom: double black; border-top: 1px solid black; font-style: italic; font-size: 0.9em;">Computed correlation used pearson-method with listwise-deletion.</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(M)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="desigualdad-pp3_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Como se puede observar, la matriz de correlación muestra las relaciones entre diversas variables socioeconómicas y de participación política. Se observa que la participación en distintas actividades políticas (causa, marcha, huelga, RRSS, movimientos sociales) tiene correlaciones positivas moderadas a fuertes entre sí, indicando que los individuos que participan en una actividad tienden a participar en otras. El interés político también muestra una correlación positiva con la autoubicación política, sugiriendo que aquellos con mayor interés político tienden a posicionarse más claramente en el espectro político. Por otro lado, la edad presenta correlaciones negativas con la participación en actividades como RRSS y movimientos sociales, lo que indica que los individuos más jóvenes tienden a participar más en estas actividades. Aunque la percepción de desigualdad está relacionada con la participación política, estas correlaciones no son tan fuertes, sugiriendo una relación más compleja que podría estar influenciada por otros factores.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>M2 <span class="ot">&lt;-</span> <span class="fu">cor</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(proc_data, percep_desigualdad, apoyo_causa, part_marcha, part_huelga, rrss_pol, pert_pp, interes_pol, part_movsoc, NSE), <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(M2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="desigualdad-pp3_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La matriz de correlación muestra las relaciones entre la percepción de desigualdad, diversas formas de participación política y el nivel socioeconómico (NSE). Se observa que la percepción de desigualdad está positivamente correlacionada con la participación en marchas (r = 0.30), huelgas (r = 0.44), redes sociales (RRSS) (r = 0.34), pertenencia a partidos políticos (r = 0.22), interés político (r = 0.34) y movimientos sociales (r = 0.36). Estas correlaciones sugieren que quienes perciben desigualdad tienden a participar más activamente en diversas actividades políticas. Comparando con la matriz anterior, que también muestra interrelaciones positivas entre diferentes formas de participación política y destaca la influencia negativa de la edad en la participación en RRSS y movimientos sociales, esta nueva matriz enfatiza la importancia de la percepción de desigualdad como un factor motivador clave para la participación política.</p>
</section>
<section id="alfa-de-cronbach" class="level2">
<h2 class="anchored" data-anchor-id="alfa-de-cronbach">Alfa de Cronbach</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(proc_data, apoyo_causa, part_marcha, part_huelga, percep_desigualdad,</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>                           rrss_pol, pert_pp, interes_pol, part_movsoc, NSE, educacion, edad, sexo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in psych::alpha(dplyr::select(proc_data, apoyo_causa, part_marcha, : Some items were negatively correlated with the first principal component and probably 
should be reversed.  
To do this, run the function again with the 'check.keys=TRUE' option</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Some items ( edad sexo ) were negatively correlated with the first principal component and 
probably should be reversed.  
To do this, run the function again with the 'check.keys=TRUE' option</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = dplyr::select(proc_data, apoyo_causa, part_marcha, 
    part_huelga, percep_desigualdad, rrss_pol, pert_pp, interes_pol, 
    part_movsoc, NSE, educacion, edad, sexo))

  raw_alpha std.alpha G6(smc) average_r S/N   ase mean  sd median_r
    -0.095      0.54    0.58     0.089 1.2 0.014  5.3 1.3    0.075

    95% confidence boundaries 
         lower alpha upper
Feldt    -0.19 -0.09  0.00
Duhachek -0.12 -0.09 -0.07

 Reliability if an item is dropped:
                   raw_alpha std.alpha G6(smc) average_r  S/N alpha se var.r
apoyo_causa           -0.092      0.49    0.53     0.079 0.94    0.012 0.025
part_marcha           -0.088      0.46    0.50     0.072 0.85    0.012 0.020
part_huelga           -0.094      0.49    0.53     0.082 0.98    0.013 0.024
percep_desigualdad    -0.100      0.54    0.58     0.098 1.20    0.013 0.028
rrss_pol              -0.067      0.48    0.52     0.077 0.92    0.012 0.021
pert_pp               -0.098      0.52    0.56     0.090 1.09    0.013 0.027
interes_pol           -0.090      0.47    0.52     0.075 0.89    0.012 0.024
part_movsoc           -0.085      0.48    0.52     0.077 0.92    0.012 0.023
NSE                   -0.095      0.54    0.57     0.097 1.17    0.013 0.027
educacion             -0.069      0.50    0.54     0.083 1.00    0.011 0.024
edad                   0.628      0.62    0.63     0.127 1.61    0.015 0.017
sexo                  -0.103      0.58    0.61     0.113 1.40    0.014 0.025
                   med.r
apoyo_causa        0.069
part_marcha        0.070
part_huelga        0.070
percep_desigualdad 0.101
rrss_pol           0.067
pert_pp            0.070
interes_pol        0.069
part_movsoc        0.070
NSE                0.101
educacion          0.067
edad               0.103
sexo               0.103

 Item statistics 
                      n   raw.r  std.r  r.cor  r.drop mean    sd
apoyo_causa        1181 -0.0032  0.522  0.461 -0.0432  1.4  0.60
part_marcha        1181 -0.0551  0.602  0.609 -0.0898  1.2  0.53
part_huelga        1181 -0.0045  0.491  0.432 -0.0320  1.1  0.41
percep_desigualdad 1181  0.0840  0.306  0.139  0.0474  2.8  0.55
rrss_pol           1181 -0.1898  0.543  0.515 -0.2383  1.5  0.77
pert_pp            1181  0.0641  0.397  0.276  0.0470  1.1  0.26
interes_pol        1181 -0.0052  0.563  0.528 -0.0539  1.7  0.73
part_movsoc        1181 -0.0635  0.541  0.500 -0.1046  1.3  0.62
NSE                1181  0.0256  0.323  0.182 -0.0092  1.5  0.52
educacion          1181 -0.1266  0.471  0.407 -0.1863  3.0  0.92
edad               1181  0.9803 -0.026 -0.264 -0.2619 45.1 15.52
sexo               1181  0.1208  0.141 -0.077  0.0881  1.6  0.49

Non missing response frequency for each item
                      1    2    3    4 miss
apoyo_causa        0.71 0.23 0.07 0.00    0
part_marcha        0.83 0.12 0.05 0.00    0
part_huelga        0.89 0.08 0.03 0.00    0
percep_desigualdad 0.08 0.03 0.89 0.00    0
rrss_pol           0.68 0.15 0.17 0.00    0
pert_pp            0.93 0.07 0.00 0.00    0
interes_pol        0.49 0.35 0.16 0.00    0
part_movsoc        0.76 0.16 0.08 0.00    0
NSE                0.52 0.46 0.01 0.00    0
educacion          0.08 0.21 0.39 0.32    0
sexo               0.43 0.57 0.00 0.00    0</code></pre>
</div>
</div>
<p>El coeficiente de Alfa de Cronbach calculado para el conjunto de ítems es de 0.54 al 95% de confianza, lo que indica una consistencia moderada de las respuestas entre los ítems relacionados. En otras palabras, sugiere que la confiabilidad de los ítems es moderada y que hay una relación intermedia entre las variables seleccionadas. Esto implica que, aunque las variables comparten cierta consistencia, no es lo suficientemente alta como para asegurar una fuerte relación entre ellas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(proc_data, apoyo_causa, part_marcha, part_huelga, rrss_pol, pert_pp, part_movsoc))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = dplyr::select(proc_data, apoyo_causa, part_marcha, 
    part_huelga, rrss_pol, pert_pp, part_movsoc))

  raw_alpha std.alpha G6(smc) average_r S/N   ase mean   sd median_r
      0.65      0.66    0.63      0.24 1.9 0.014  1.3 0.34     0.24

    95% confidence boundaries 
         lower alpha upper
Feldt     0.62  0.65  0.68
Duhachek  0.63  0.65  0.68

 Reliability if an item is dropped:
            raw_alpha std.alpha G6(smc) average_r S/N alpha se  var.r med.r
apoyo_causa      0.61      0.62    0.59      0.25 1.6    0.016 0.0121  0.23
part_marcha      0.56      0.56    0.51      0.20 1.3    0.018 0.0058  0.22
part_huelga      0.62      0.61    0.57      0.24 1.6    0.016 0.0086  0.27
rrss_pol         0.61      0.60    0.57      0.23 1.5    0.017 0.0117  0.23
pert_pp          0.66      0.68    0.64      0.30 2.1    0.015 0.0048  0.30
part_movsoc      0.60      0.60    0.57      0.23 1.5    0.017 0.0122  0.22

 Item statistics 
               n raw.r std.r r.cor r.drop mean   sd
apoyo_causa 1181  0.62  0.59  0.45   0.38  1.4 0.60
part_marcha 1181  0.70  0.72  0.67   0.53  1.2 0.53
part_huelga 1181  0.56  0.61  0.49   0.39  1.1 0.41
rrss_pol    1181  0.71  0.63  0.51   0.43  1.5 0.77
pert_pp     1181  0.32  0.46  0.25   0.20  1.1 0.26
part_movsoc 1181  0.66  0.64  0.52   0.43  1.3 0.62

Non missing response frequency for each item
               1    2    3 miss
apoyo_causa 0.71 0.23 0.07    0
part_marcha 0.83 0.12 0.05    0
part_huelga 0.89 0.08 0.03    0
rrss_pol    0.68 0.15 0.17    0
pert_pp     0.93 0.07 0.00    0
part_movsoc 0.76 0.16 0.08    0</code></pre>
</div>
</div>
<p>El coeficiente de Alfa de Cronbach calculado para el conjunto de ítems es de 0.61 al 95% de confianza, lo que indica una consistencia interna moderada entre las respuestas de los ítems relacionados. Esto sugiere que la confiabilidad de los ítems es adecuada.</p>
</section>
<section id="construcción-de-escala" class="level2">
<h2 class="anchored" data-anchor-id="construcción-de-escala">Construcción de Escala</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> </span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">participacion_politica =</span> <span class="fu">sum</span>(apoyo_causa, part_marcha, part_huelga, </span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>                                      rrss_pol, pert_pp, part_movsoc, interes_pol, autoubicpol))</span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_data<span class="sc">$</span>participacion_politica)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    8.0     9.0    11.0    11.2    12.0    23.0 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(proc_data, <span class="fu">aes</span>(<span class="at">x =</span> participacion_politica)) <span class="sc">+</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.6</span>, <span class="at">colour=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"yellow"</span>) <span class="sc">+</span></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Participación Política"</span>) <span class="sc">+</span></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Cantidad"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="desigualdad-pp3_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La escala de participación política calculada muestra una variabilidad significativa en la participación política de los individuos, con la mayoría de las puntuaciones concentradas en el rango de 9 a 12. La media y la mediana cercanas indican una distribución relativamente simétrica de las puntuaciones, aunque la existencia de valores máximos más altos sugiere que algunos individuos son mucho más activos políticamente.</p>
<p>Luego de construida la escala, el gráfico muestra una distribución asimétrica de la participación política, con una mayor concentración de individuos en las puntuaciones más bajas de la escala. La moda se encuentra alrededor de 10, indicando que la mayoría de los individuos tiene una baja participación política. A medida que aumentan las puntuaciones, la frecuencia de individuos disminuye de manera constante, con muy pocos individuos alcanzando las puntuaciones más altas por encima de 20. Este patrón sugiere que la participación política es predominantemente baja en el conjunto de datos, con pocas personas participando activamente en actividades políticas.</p>
</section>
<section id="regresión-lineal" class="level2">
<h2 class="anchored" data-anchor-id="regresión-lineal">Regresión Lineal</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>proc_data_reg <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(participacion_politica, edad, NSE, sexo, educacion, percep_desigualdad)</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cor</span>(proc_data_reg, <span class="at">use =</span> <span class="st">"complete.obs"</span>) </span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(M) <span class="ot">=</span> <span class="cn">NA</span> </span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(M) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"A. Participación Política"</span>,</span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"B. Edad"</span>,</span>
<span id="cb100-7"><a href="#cb100-7" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"C. NSE"</span>,</span>
<span id="cb100-8"><a href="#cb100-8" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"D. Sexo"</span>,</span>
<span id="cb100-9"><a href="#cb100-9" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"E. Educación"</span>,</span>
<span id="cb100-10"><a href="#cb100-10" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"F. Percepción Desigualdad"</span>)</span>
<span id="cb100-11"><a href="#cb100-11" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(M) <span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"(A)"</span>, <span class="st">"(B)"</span>,<span class="st">"(C)"</span>, <span class="st">"(D)"</span>, <span class="st">"(E)"</span>,<span class="st">"(F)"</span>)</span>
<span id="cb100-12"><a href="#cb100-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-13"><a href="#cb100-13" aria-hidden="true" tabindex="-1"></a>corrplot<span class="sc">::</span><span class="fu">corrplot</span>(M,</span>
<span id="cb100-14"><a href="#cb100-14" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method =</span> <span class="st">"color"</span>, </span>
<span id="cb100-15"><a href="#cb100-15" aria-hidden="true" tabindex="-1"></a>                   <span class="at">addCoef.col =</span> <span class="st">"#000390"</span>, </span>
<span id="cb100-16"><a href="#cb100-16" aria-hidden="true" tabindex="-1"></a>                   <span class="at">type =</span> <span class="st">"upper"</span>, </span>
<span id="cb100-17"><a href="#cb100-17" aria-hidden="true" tabindex="-1"></a>                   <span class="at">tl.col =</span> <span class="st">"black"</span>, </span>
<span id="cb100-18"><a href="#cb100-18" aria-hidden="true" tabindex="-1"></a>                   <span class="at">na.label =</span> <span class="st">"-"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="desigualdad-pp3_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>El gráfico de correlación muestra las relaciones entre varias variables socioeconómicas y la participación política. La participación política tiene una correlación negativa moderada con la edad (-0.25), lo que sugiere que los individuos mayores tienden a participar menos en actividades políticas. También se observa una correlación positiva moderada con la educación (0.31), indicando que un mayor nivel educativo está asociado con una mayor participación política. El nivel socioeconómico y el sexo muestran correlaciones muy débiles con la participación política (-0.05 y -0.01 respectivamente). Además, la percepción de desigualdad tiene una correlación positiva baja (0.06), sugiriendo que aquellos que perciben desigualdad tienden a participar ligeramente más en actividades políticas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Variable dependiente: Participación Política</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_data<span class="sc">$</span>participacion_politica)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    8.0     9.0    11.0    11.2    12.0    23.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>proc_data_reg <span class="ot">&lt;-</span> proc_data_reg <span class="sc">%&gt;%</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sexo =</span> <span class="fu">case_when</span>(sexo <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">1</span>, <span class="co">#Para Hombres</span></span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>                          sexo <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">0</span>)) <span class="co">#Para Mujeres</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="construcción-de-modelos" class="level3">
<h3 class="anchored" data-anchor-id="construcción-de-modelos">Construcción de Modelos</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>fit01 <span class="ot">&lt;-</span> <span class="fu">lm</span>(participacion_politica <span class="sc">~</span> percep_desigualdad <span class="sc">+</span> sexo <span class="sc">+</span> NSE <span class="sc">+</span> educacion <span class="sc">+</span> edad, <span class="at">data =</span> proc_data_reg)</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>fit02 <span class="ot">&lt;-</span> <span class="fu">lm</span>(participacion_politica <span class="sc">~</span> percep_desigualdad <span class="sc">+</span> sexo <span class="sc">+</span> NSE <span class="sc">+</span> educacion, <span class="at">data =</span> proc_data_reg)</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>fit03 <span class="ot">&lt;-</span> <span class="fu">lm</span>(participacion_politica <span class="sc">~</span> percep_desigualdad <span class="sc">+</span> sexo <span class="sc">+</span> NSE, <span class="at">data =</span> proc_data_reg)</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>fit04 <span class="ot">&lt;-</span> <span class="fu">lm</span>(participacion_politica <span class="sc">~</span> percep_desigualdad <span class="sc">+</span> sexo, <span class="at">data =</span> proc_data_reg)</span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>fit05 <span class="ot">&lt;-</span> <span class="fu">lm</span>(participacion_politica <span class="sc">~</span> percep_desigualdad, <span class="at">data =</span> proc_data_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Verificar el número de coeficientes en un modelo para asegurarse de que custom.coef.names tenga la longitud correcta</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">coef</span>(fit01))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definir los nombres personalizados para los coeficientes</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>custom_coef_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Intercepto"</span>, <span class="st">"Percepción Desigualdad"</span>, <span class="st">"Sexo (mujer)"</span>, <span class="st">"NSE Medio/NSE Alto"</span>, <span class="st">"Educación"</span>, <span class="st">"Edad"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Mostrar los resultados de los modelos con nombres personalizados para los modelos y coeficientes</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">screenreg</span>(<span class="fu">list</span>(fit01, fit02, fit03, fit04, fit05),</span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">custom.model.names =</span> <span class="fu">c</span>(<span class="st">"Modelo 1"</span>, <span class="st">"Modelo 2"</span>, <span class="st">"Modelo 3"</span>, <span class="st">"Modelo 4"</span>, <span class="st">"Modelo 5"</span>),</span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">custom.coef.names =</span> custom_coef_names)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=======================================================================================
                        Modelo 1     Modelo 2     Modelo 3     Modelo 4     Modelo 5   
---------------------------------------------------------------------------------------
Intercepto                 9.96 ***     8.38 ***     9.80 ***    10.37 ***    10.50 ***
                          (0.47)       (0.41)       (0.41)       (0.37)       (0.36)   
Percepción Desigualdad     0.17         0.13         0.22         0.25 *       0.25    
                          (0.12)       (0.12)       (0.13)       (0.13)       (0.13)   
Sexo (mujer)               0.07         0.15         0.24         0.27                 
                          (0.13)       (0.14)       (0.14)       (0.14)                
NSE Medio/NSE Alto         0.08         0.05         0.45 ***                          
                          (0.13)       (0.13)       (0.13)                             
Educación                  0.66 ***     0.78 ***                                       
                          (0.08)       (0.08)                                          
Edad                      -0.03 ***                                                    
                          (0.00)                                                       
---------------------------------------------------------------------------------------
R^2                        0.13         0.10         0.02         0.01         0.00    
Adj. R^2                   0.13         0.09         0.01         0.00         0.00    
Num. obs.               1181         1181         1181         1181         1181       
=======================================================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
<p>Para profundizar en el análisis, se realizó una regresión lineal con el fin de validar o rechazar la hipótesis de que la participación política está altamente asociada a la percepción de desigualdad. Este método también permite evaluar cómo otras variables, como sexo, edad, nivel socioeconómico (NSE) y nivel educacional, influyen en la participación política. En este análisis, la variable dependiente es la participación política.<br>
<br>
En el modelo 1, la educación y la edad resultan ser variables significativamente asociadas a la participación política. La educación muestra un efecto positivo fuerte, mientras que la edad muestra un efecto negativo significativo. La percepción de desigualdad, el sexo y el NSE no son significativos.</p>
<p>En el modelo 2, al eliminar la variable edad, la educación sigue siendo significativa, aunque el poder explicativo del modelo (R^2) disminuye ligeramente, lo que sugiere que la edad también contribuye a explicar la variabilidad en la participación política.</p>
<p>En el modelo 3, al excluir la educación y la edad, el NSE Medio/Alto se vuelve significativo, lo que sugiere que el nivel socioeconómico tiene un efecto positivo sobre la participación política cuando no se controla por la educación.</p>
<p>El modelo 4 se enfoca en la percepción de desigualdad y el sexo. La percepción de desigualdad se vuelve significativa con un efecto positivo, aunque el R^2 sigue siendo bajo, indicando una capacidad explicativa limitada del modelo.</p>
<p>El último modelo (5), que solo incluye la percepción de desigualdad, muestra que esta variable, aunque con un coeficiente positivo, no es significativa, y el R^2 es prácticamente nulo, indicando que este modelo no explica bien la variabilidad en la participación política.</p>
<p>El análisis de regresión revela que la educación y la edad son los predictores más robustos de la participación política, con la educación aumentando y la edad disminuyendo la participación. El nivel socioeconómico también muestra un impacto significativo cuando no se controla por la educación, sugiriendo una interacción entre estas variables. La percepción de desigualdad, aunque significativa en un modelo, tiene un efecto limitado. El sexo no parece influir significativamente en la participación política.</p>

</section>
</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-castilloSocialInequalityChanges2014" class="csl-entry" role="listitem">
Castillo, Juan C, Daniel Miranda, Macarena Bonhomme, Cristián Cox, and Martín Bascopé. 2014. <span>“Social Inequality and Changes in Students’ Expected Political Participation in <span>Chile</span>.”</span> <em>Education, Citizenship and Social Justice</em> 9 (2): 140–56. <a href="https://doi.org/10.1177/1746197914520650">https://doi.org/10.1177/1746197914520650</a>.
</div>
<div id="ref-diegocolladoEffectsClassroomSocioeconomic2015" class="csl-entry" role="listitem">
Diego Collado, Diego Collado, Catalina Lomos, Catalina Lomos, Idès Nicaise, and Ides Nicaise. 2015. <span>“The Effects of Classroom Socioeconomic Composition on Student’s Civic Knowledge in <span>Chile</span>.”</span> <em>School Effectiveness and School Improvement</em> 26 (3): 415–40. <a href="https://doi.org/10.1080/09243453.2014.966725">https://doi.org/10.1080/09243453.2014.966725</a>.
</div>
<div id="ref-juancarloscastilloMitigatingPoliticalParticipation2015" class="csl-entry" role="listitem">
Juan Carlos Castillo, Juan Carlos Castillo, Daniel Miranda, Daniel Miranda, Macarena Bonhomme, Macarena Bonhomme, Cristián Cox, Cristián Cox, Martín Bascopé, and Martín Bascopé. 2015. <span>“Mitigating the Political Participation Gap from the School: The Roles of Civic Knowledge and Classroom Climate.”</span> <em>Journal of Youth Studies</em> 18 (1): 16–35. <a href="https://doi.org/10.1080/13676261.2014.933199">https://doi.org/10.1080/13676261.2014.933199</a>.
</div>
<div id="ref-marchoogheVotersCandidatesFuture2013" class="csl-entry" role="listitem">
Marc Hooghe, Ruth Dassonneville, Ruth Dassonneville, and Marc Hooghe. 2013. <span>“Voters and <span>Candidates</span> of the <span>Future</span>: <span>The Intention</span> of <span>Electoral Participation</span> Among <span>Adolescents</span> in 22 <span>European Countries</span>:”</span> 21 (1): 1–28. <a href="https://doi.org/10.1177/1103308812467664">https://doi.org/10.1177/1103308812467664</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>